# .goreleaser.yml
# This file is used by the Release GitHub Action to build and distribute the Pulumi Netbird provider.
version: 1

project_name: pulumi-resource-netbird

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: pulumi-resource-netbird
    main: ./cmd/pulumi-resource-netbird
    binary: pulumi-resource-netbird
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}

archives:
  - formats: ["tar.gz", "zip"]
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: KitStream
    name: netbird-pulumi-provider
  prerelease: auto
