// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/peer:Peer")]
    public partial class Peer : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Indicates whether peer needs approval
        /// </summary>
        [Output("approvalRequired")]
        public Output<bool> ApprovalRequired { get; private set; } = null!;

        /// <summary>
        /// Peer city name
        /// </summary>
        [Output("cityName")]
        public Output<string> CityName { get; private set; } = null!;

        /// <summary>
        /// Peer Connection Status
        /// </summary>
        [Output("connected")]
        public Output<bool> Connected { get; private set; } = null!;

        /// <summary>
        /// Peer Public IP
        /// </summary>
        [Output("connectionIp")]
        public Output<string> ConnectionIp { get; private set; } = null!;

        /// <summary>
        /// Peer country code
        /// </summary>
        [Output("countryCode")]
        public Output<string> CountryCode { get; private set; } = null!;

        /// <summary>
        /// Peer DNS Label
        /// </summary>
        [Output("dnsLabel")]
        public Output<string> DnsLabel { get; private set; } = null!;

        /// <summary>
        /// Peer extra DNS Labels
        /// </summary>
        [Output("extraDnsLabels")]
        public Output<ImmutableArray<string>> ExtraDnsLabels { get; private set; } = null!;

        /// <summary>
        /// Peer Location ID
        /// </summary>
        [Output("geonameId")]
        public Output<int> GeonameId { get; private set; } = null!;

        /// <summary>
        /// Peer groups
        /// </summary>
        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        /// <summary>
        /// Peer's HOSTNAME
        /// </summary>
        [Output("hostname")]
        public Output<string> Hostname { get; private set; } = null!;

        /// <summary>
        /// Enable inactivity expiration for peer
        /// </summary>
        [Output("inactivityExpirationEnabled")]
        public Output<bool> InactivityExpirationEnabled { get; private set; } = null!;

        /// <summary>
        /// Peer  IP
        /// </summary>
        [Output("ip")]
        public Output<string> Ip { get; private set; } = null!;

        /// <summary>
        /// Peer Kernel Version
        /// </summary>
        [Output("kernelVersion")]
        public Output<string> KernelVersion { get; private set; } = null!;

        /// <summary>
        /// Time of peer last login
        /// </summary>
        [Output("lastLogin")]
        public Output<string> LastLogin { get; private set; } = null!;

        /// <summary>
        /// Peer Last Seen timedate
        /// </summary>
        [Output("lastSeen")]
        public Output<string> LastSeen { get; private set; } = null!;

        /// <summary>
        /// Indicates whether login expiration is enabled for peer
        /// </summary>
        [Output("loginExpirationEnabled")]
        public Output<bool> LoginExpirationEnabled { get; private set; } = null!;

        /// <summary>
        /// Indicates whether peer login is expired
        /// </summary>
        [Output("loginExpired")]
        public Output<bool> LoginExpired { get; private set; } = null!;

        /// <summary>
        /// Peer Name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Peer OS
        /// </summary>
        [Output("os")]
        public Output<string> Os { get; private set; } = null!;

        /// <summary>
        /// Peer ID
        /// </summary>
        [Output("peerId")]
        public Output<string> PeerId { get; private set; } = null!;

        /// <summary>
        /// Peer device serial number
        /// </summary>
        [Output("serialNumber")]
        public Output<string> SerialNumber { get; private set; } = null!;

        /// <summary>
        /// Enable SSH to Peer
        /// </summary>
        [Output("sshEnabled")]
        public Output<bool> SshEnabled { get; private set; } = null!;

        /// <summary>
        /// Peer  UI Version
        /// </summary>
        [Output("uiVersion")]
        public Output<string> UiVersion { get; private set; } = null!;

        /// <summary>
        /// User ID of peer
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;

        /// <summary>
        /// Peer  Version
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Peer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Peer(string name, PeerArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/peer:Peer", name, args ?? new PeerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Peer(string name, Input<string> id, PeerState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/peer:Peer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Peer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Peer Get(string name, Input<string> id, PeerState? state = null, CustomResourceOptions? options = null)
        {
            return new Peer(name, id, state, options);
        }
    }

    public sealed class PeerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates whether peer needs approval
        /// </summary>
        [Input("approvalRequired")]
        public Input<bool>? ApprovalRequired { get; set; }

        /// <summary>
        /// Enable inactivity expiration for peer
        /// </summary>
        [Input("inactivityExpirationEnabled")]
        public Input<bool>? InactivityExpirationEnabled { get; set; }

        /// <summary>
        /// Indicates whether login expiration is enabled for peer
        /// </summary>
        [Input("loginExpirationEnabled")]
        public Input<bool>? LoginExpirationEnabled { get; set; }

        /// <summary>
        /// Peer Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Peer ID
        /// </summary>
        [Input("peerId", required: true)]
        public Input<string> PeerId { get; set; } = null!;

        /// <summary>
        /// Enable SSH to Peer
        /// </summary>
        [Input("sshEnabled")]
        public Input<bool>? SshEnabled { get; set; }

        public PeerArgs()
        {
        }
        public static new PeerArgs Empty => new PeerArgs();
    }

    public sealed class PeerState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates whether peer needs approval
        /// </summary>
        [Input("approvalRequired")]
        public Input<bool>? ApprovalRequired { get; set; }

        /// <summary>
        /// Peer city name
        /// </summary>
        [Input("cityName")]
        public Input<string>? CityName { get; set; }

        /// <summary>
        /// Peer Connection Status
        /// </summary>
        [Input("connected")]
        public Input<bool>? Connected { get; set; }

        /// <summary>
        /// Peer Public IP
        /// </summary>
        [Input("connectionIp")]
        public Input<string>? ConnectionIp { get; set; }

        /// <summary>
        /// Peer country code
        /// </summary>
        [Input("countryCode")]
        public Input<string>? CountryCode { get; set; }

        /// <summary>
        /// Peer DNS Label
        /// </summary>
        [Input("dnsLabel")]
        public Input<string>? DnsLabel { get; set; }

        [Input("extraDnsLabels")]
        private InputList<string>? _extraDnsLabels;

        /// <summary>
        /// Peer extra DNS Labels
        /// </summary>
        public InputList<string> ExtraDnsLabels
        {
            get => _extraDnsLabels ?? (_extraDnsLabels = new InputList<string>());
            set => _extraDnsLabels = value;
        }

        /// <summary>
        /// Peer Location ID
        /// </summary>
        [Input("geonameId")]
        public Input<int>? GeonameId { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;

        /// <summary>
        /// Peer groups
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// Peer's HOSTNAME
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// Enable inactivity expiration for peer
        /// </summary>
        [Input("inactivityExpirationEnabled")]
        public Input<bool>? InactivityExpirationEnabled { get; set; }

        /// <summary>
        /// Peer  IP
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        /// <summary>
        /// Peer Kernel Version
        /// </summary>
        [Input("kernelVersion")]
        public Input<string>? KernelVersion { get; set; }

        /// <summary>
        /// Time of peer last login
        /// </summary>
        [Input("lastLogin")]
        public Input<string>? LastLogin { get; set; }

        /// <summary>
        /// Peer Last Seen timedate
        /// </summary>
        [Input("lastSeen")]
        public Input<string>? LastSeen { get; set; }

        /// <summary>
        /// Indicates whether login expiration is enabled for peer
        /// </summary>
        [Input("loginExpirationEnabled")]
        public Input<bool>? LoginExpirationEnabled { get; set; }

        /// <summary>
        /// Indicates whether peer login is expired
        /// </summary>
        [Input("loginExpired")]
        public Input<bool>? LoginExpired { get; set; }

        /// <summary>
        /// Peer Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Peer OS
        /// </summary>
        [Input("os")]
        public Input<string>? Os { get; set; }

        /// <summary>
        /// Peer ID
        /// </summary>
        [Input("peerId")]
        public Input<string>? PeerId { get; set; }

        /// <summary>
        /// Peer device serial number
        /// </summary>
        [Input("serialNumber")]
        public Input<string>? SerialNumber { get; set; }

        /// <summary>
        /// Enable SSH to Peer
        /// </summary>
        [Input("sshEnabled")]
        public Input<bool>? SshEnabled { get; set; }

        /// <summary>
        /// Peer  UI Version
        /// </summary>
        [Input("uiVersion")]
        public Input<string>? UiVersion { get; set; }

        /// <summary>
        /// User ID of peer
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        /// <summary>
        /// Peer  Version
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public PeerState()
        {
        }
        public static new PeerState Empty => new PeerState();
    }
}
