// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/personalAccessToken:PersonalAccessToken")]
    public partial class PersonalAccessToken : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Token Expiration Date
        /// </summary>
        [Output("expirationDate")]
        public Output<string> ExpirationDate { get; private set; } = null!;

        [Output("expirationDays")]
        public Output<int> ExpirationDays { get; private set; } = null!;

        /// <summary>
        /// Last usage time
        /// </summary>
        [Output("lastUsed")]
        public Output<string> LastUsed { get; private set; } = null!;

        /// <summary>
        /// Token Name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Plaintext token
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        /// <summary>
        /// User ID
        /// </summary>
        [Output("userId")]
        public Output<string> UserId { get; private set; } = null!;


        /// <summary>
        /// Create a PersonalAccessToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PersonalAccessToken(string name, PersonalAccessTokenArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/personalAccessToken:PersonalAccessToken", name, args ?? new PersonalAccessTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PersonalAccessToken(string name, Input<string> id, PersonalAccessTokenState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/personalAccessToken:PersonalAccessToken", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "token",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PersonalAccessToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PersonalAccessToken Get(string name, Input<string> id, PersonalAccessTokenState? state = null, CustomResourceOptions? options = null)
        {
            return new PersonalAccessToken(name, id, state, options);
        }
    }

    public sealed class PersonalAccessTokenArgs : global::Pulumi.ResourceArgs
    {
        [Input("expirationDays", required: true)]
        public Input<int> ExpirationDays { get; set; } = null!;

        /// <summary>
        /// Token Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// User ID
        /// </summary>
        [Input("userId", required: true)]
        public Input<string> UserId { get; set; } = null!;

        public PersonalAccessTokenArgs()
        {
        }
        public static new PersonalAccessTokenArgs Empty => new PersonalAccessTokenArgs();
    }

    public sealed class PersonalAccessTokenState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Token Expiration Date
        /// </summary>
        [Input("expirationDate")]
        public Input<string>? ExpirationDate { get; set; }

        [Input("expirationDays")]
        public Input<int>? ExpirationDays { get; set; }

        /// <summary>
        /// Last usage time
        /// </summary>
        [Input("lastUsed")]
        public Input<string>? LastUsed { get; set; }

        /// <summary>
        /// Token Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Plaintext token
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// User ID
        /// </summary>
        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public PersonalAccessTokenState()
        {
        }
        public static new PersonalAccessTokenState Empty => new PersonalAccessTokenState();
    }
}
