// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"context"
	"reflect"

	"github.com/KitStream/pulumi-netbird/sdk/go/index/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetToken(ctx *pulumi.Context, args *GetTokenArgs, opts ...pulumi.InvokeOption) (*GetTokenResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTokenResult
	err := ctx.Invoke("netbird:index/getToken:getToken", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getToken.
type GetTokenArgs struct {
	Id     *string `pulumi:"id"`
	Name   *string `pulumi:"name"`
	UserId string  `pulumi:"userId"`
}

// A collection of values returned by getToken.
type GetTokenResult struct {
	CreatedAt      string `pulumi:"createdAt"`
	ExpirationDate string `pulumi:"expirationDate"`
	Id             string `pulumi:"id"`
	LastUsed       string `pulumi:"lastUsed"`
	Name           string `pulumi:"name"`
	UserId         string `pulumi:"userId"`
}

func GetTokenOutput(ctx *pulumi.Context, args GetTokenOutputArgs, opts ...pulumi.InvokeOption) GetTokenResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetTokenResultOutput, error) {
			args := v.(GetTokenArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbird:index/getToken:getToken", args, GetTokenResultOutput{}, options).(GetTokenResultOutput), nil
		}).(GetTokenResultOutput)
}

// A collection of arguments for invoking getToken.
type GetTokenOutputArgs struct {
	Id     pulumi.StringPtrInput `pulumi:"id"`
	Name   pulumi.StringPtrInput `pulumi:"name"`
	UserId pulumi.StringInput    `pulumi:"userId"`
}

func (GetTokenOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenArgs)(nil)).Elem()
}

// A collection of values returned by getToken.
type GetTokenResultOutput struct{ *pulumi.OutputState }

func (GetTokenResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenResult)(nil)).Elem()
}

func (o GetTokenResultOutput) ToGetTokenResultOutput() GetTokenResultOutput {
	return o
}

func (o GetTokenResultOutput) ToGetTokenResultOutputWithContext(ctx context.Context) GetTokenResultOutput {
	return o
}

func (o GetTokenResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o GetTokenResultOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenResult) string { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o GetTokenResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTokenResultOutput) LastUsed() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenResult) string { return v.LastUsed }).(pulumi.StringOutput)
}

func (o GetTokenResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetTokenResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenResult) string { return v.UserId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTokenResultOutput{})
}
