// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"fmt"

	"github.com/KitStream/pulumi-netbird/sdk/go/index/internal"
	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "netbird:index/accountSettings:AccountSettings":
		r = &AccountSettings{}
	case "netbird:index/dnsSettings:DnsSettings":
		r = &DnsSettings{}
	case "netbird:index/group:Group":
		r = &Group{}
	case "netbird:index/nameserverGroup:NameserverGroup":
		r = &NameserverGroup{}
	case "netbird:index/network:Network":
		r = &Network{}
	case "netbird:index/networkResource:NetworkResource":
		r = &NetworkResource{}
	case "netbird:index/networkRouter:NetworkRouter":
		r = &NetworkRouter{}
	case "netbird:index/peer:Peer":
		r = &Peer{}
	case "netbird:index/personalAccessToken:PersonalAccessToken":
		r = &PersonalAccessToken{}
	case "netbird:index/policy:Policy":
		r = &Policy{}
	case "netbird:index/postureCheck:PostureCheck":
		r = &PostureCheck{}
	case "netbird:index/route:Route":
		r = &Route{}
	case "netbird:index/setupKey:SetupKey":
		r = &SetupKey{}
	case "netbird:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:netbird" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"netbird",
		"index/accountSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/dnsSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/nameserverGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/networkResource",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/networkRouter",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/peer",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/personalAccessToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/policy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/postureCheck",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/route",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/setupKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"netbird",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"netbird",
		&pkg{version},
	)
}
