// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package index

import (
	"context"
	"reflect"

	"errors"
	"github.com/KitStream/pulumi-netbird/sdk/go/index/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Peer struct {
	pulumi.CustomResourceState

	// Indicates whether peer needs approval
	ApprovalRequired pulumi.BoolOutput `pulumi:"approvalRequired"`
	// Peer city name
	CityName pulumi.StringOutput `pulumi:"cityName"`
	// Peer Connection Status
	Connected pulumi.BoolOutput `pulumi:"connected"`
	// Peer Public IP
	ConnectionIp pulumi.StringOutput `pulumi:"connectionIp"`
	// Peer country code
	CountryCode pulumi.StringOutput `pulumi:"countryCode"`
	// Peer DNS Label
	DnsLabel pulumi.StringOutput `pulumi:"dnsLabel"`
	// Peer extra DNS Labels
	ExtraDnsLabels pulumi.StringArrayOutput `pulumi:"extraDnsLabels"`
	// Peer Location ID
	GeonameId pulumi.IntOutput `pulumi:"geonameId"`
	// Peer groups
	Groups pulumi.StringArrayOutput `pulumi:"groups"`
	// Peer's HOSTNAME
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// Enable inactivity expiration for peer
	InactivityExpirationEnabled pulumi.BoolOutput `pulumi:"inactivityExpirationEnabled"`
	// Peer  IP
	Ip pulumi.StringOutput `pulumi:"ip"`
	// Peer Kernel Version
	KernelVersion pulumi.StringOutput `pulumi:"kernelVersion"`
	// Time of peer last login
	LastLogin pulumi.StringOutput `pulumi:"lastLogin"`
	// Peer Last Seen timedate
	LastSeen pulumi.StringOutput `pulumi:"lastSeen"`
	// Indicates whether login expiration is enabled for peer
	LoginExpirationEnabled pulumi.BoolOutput `pulumi:"loginExpirationEnabled"`
	// Indicates whether peer login is expired
	LoginExpired pulumi.BoolOutput `pulumi:"loginExpired"`
	// Peer Name
	Name pulumi.StringOutput `pulumi:"name"`
	// Peer OS
	Os pulumi.StringOutput `pulumi:"os"`
	// Peer ID
	PeerId pulumi.StringOutput `pulumi:"peerId"`
	// Peer device serial number
	SerialNumber pulumi.StringOutput `pulumi:"serialNumber"`
	// Enable SSH to Peer
	SshEnabled pulumi.BoolOutput `pulumi:"sshEnabled"`
	// Peer  UI Version
	UiVersion pulumi.StringOutput `pulumi:"uiVersion"`
	// User ID of peer
	UserId pulumi.StringOutput `pulumi:"userId"`
	// Peer  Version
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewPeer registers a new resource with the given unique name, arguments, and options.
func NewPeer(ctx *pulumi.Context,
	name string, args *PeerArgs, opts ...pulumi.ResourceOption) (*Peer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PeerId == nil {
		return nil, errors.New("invalid value for required argument 'PeerId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Peer
	err := ctx.RegisterResource("netbird:index/peer:Peer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPeer gets an existing Peer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPeer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PeerState, opts ...pulumi.ResourceOption) (*Peer, error) {
	var resource Peer
	err := ctx.ReadResource("netbird:index/peer:Peer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Peer resources.
type peerState struct {
	// Indicates whether peer needs approval
	ApprovalRequired *bool `pulumi:"approvalRequired"`
	// Peer city name
	CityName *string `pulumi:"cityName"`
	// Peer Connection Status
	Connected *bool `pulumi:"connected"`
	// Peer Public IP
	ConnectionIp *string `pulumi:"connectionIp"`
	// Peer country code
	CountryCode *string `pulumi:"countryCode"`
	// Peer DNS Label
	DnsLabel *string `pulumi:"dnsLabel"`
	// Peer extra DNS Labels
	ExtraDnsLabels []string `pulumi:"extraDnsLabels"`
	// Peer Location ID
	GeonameId *int `pulumi:"geonameId"`
	// Peer groups
	Groups []string `pulumi:"groups"`
	// Peer's HOSTNAME
	Hostname *string `pulumi:"hostname"`
	// Enable inactivity expiration for peer
	InactivityExpirationEnabled *bool `pulumi:"inactivityExpirationEnabled"`
	// Peer  IP
	Ip *string `pulumi:"ip"`
	// Peer Kernel Version
	KernelVersion *string `pulumi:"kernelVersion"`
	// Time of peer last login
	LastLogin *string `pulumi:"lastLogin"`
	// Peer Last Seen timedate
	LastSeen *string `pulumi:"lastSeen"`
	// Indicates whether login expiration is enabled for peer
	LoginExpirationEnabled *bool `pulumi:"loginExpirationEnabled"`
	// Indicates whether peer login is expired
	LoginExpired *bool `pulumi:"loginExpired"`
	// Peer Name
	Name *string `pulumi:"name"`
	// Peer OS
	Os *string `pulumi:"os"`
	// Peer ID
	PeerId *string `pulumi:"peerId"`
	// Peer device serial number
	SerialNumber *string `pulumi:"serialNumber"`
	// Enable SSH to Peer
	SshEnabled *bool `pulumi:"sshEnabled"`
	// Peer  UI Version
	UiVersion *string `pulumi:"uiVersion"`
	// User ID of peer
	UserId *string `pulumi:"userId"`
	// Peer  Version
	Version *string `pulumi:"version"`
}

type PeerState struct {
	// Indicates whether peer needs approval
	ApprovalRequired pulumi.BoolPtrInput
	// Peer city name
	CityName pulumi.StringPtrInput
	// Peer Connection Status
	Connected pulumi.BoolPtrInput
	// Peer Public IP
	ConnectionIp pulumi.StringPtrInput
	// Peer country code
	CountryCode pulumi.StringPtrInput
	// Peer DNS Label
	DnsLabel pulumi.StringPtrInput
	// Peer extra DNS Labels
	ExtraDnsLabels pulumi.StringArrayInput
	// Peer Location ID
	GeonameId pulumi.IntPtrInput
	// Peer groups
	Groups pulumi.StringArrayInput
	// Peer's HOSTNAME
	Hostname pulumi.StringPtrInput
	// Enable inactivity expiration for peer
	InactivityExpirationEnabled pulumi.BoolPtrInput
	// Peer  IP
	Ip pulumi.StringPtrInput
	// Peer Kernel Version
	KernelVersion pulumi.StringPtrInput
	// Time of peer last login
	LastLogin pulumi.StringPtrInput
	// Peer Last Seen timedate
	LastSeen pulumi.StringPtrInput
	// Indicates whether login expiration is enabled for peer
	LoginExpirationEnabled pulumi.BoolPtrInput
	// Indicates whether peer login is expired
	LoginExpired pulumi.BoolPtrInput
	// Peer Name
	Name pulumi.StringPtrInput
	// Peer OS
	Os pulumi.StringPtrInput
	// Peer ID
	PeerId pulumi.StringPtrInput
	// Peer device serial number
	SerialNumber pulumi.StringPtrInput
	// Enable SSH to Peer
	SshEnabled pulumi.BoolPtrInput
	// Peer  UI Version
	UiVersion pulumi.StringPtrInput
	// User ID of peer
	UserId pulumi.StringPtrInput
	// Peer  Version
	Version pulumi.StringPtrInput
}

func (PeerState) ElementType() reflect.Type {
	return reflect.TypeOf((*peerState)(nil)).Elem()
}

type peerArgs struct {
	// Indicates whether peer needs approval
	ApprovalRequired *bool `pulumi:"approvalRequired"`
	// Enable inactivity expiration for peer
	InactivityExpirationEnabled *bool `pulumi:"inactivityExpirationEnabled"`
	// Indicates whether login expiration is enabled for peer
	LoginExpirationEnabled *bool `pulumi:"loginExpirationEnabled"`
	// Peer Name
	Name *string `pulumi:"name"`
	// Peer ID
	PeerId string `pulumi:"peerId"`
	// Enable SSH to Peer
	SshEnabled *bool `pulumi:"sshEnabled"`
}

// The set of arguments for constructing a Peer resource.
type PeerArgs struct {
	// Indicates whether peer needs approval
	ApprovalRequired pulumi.BoolPtrInput
	// Enable inactivity expiration for peer
	InactivityExpirationEnabled pulumi.BoolPtrInput
	// Indicates whether login expiration is enabled for peer
	LoginExpirationEnabled pulumi.BoolPtrInput
	// Peer Name
	Name pulumi.StringPtrInput
	// Peer ID
	PeerId pulumi.StringInput
	// Enable SSH to Peer
	SshEnabled pulumi.BoolPtrInput
}

func (PeerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*peerArgs)(nil)).Elem()
}

type PeerInput interface {
	pulumi.Input

	ToPeerOutput() PeerOutput
	ToPeerOutputWithContext(ctx context.Context) PeerOutput
}

func (*Peer) ElementType() reflect.Type {
	return reflect.TypeOf((**Peer)(nil)).Elem()
}

func (i *Peer) ToPeerOutput() PeerOutput {
	return i.ToPeerOutputWithContext(context.Background())
}

func (i *Peer) ToPeerOutputWithContext(ctx context.Context) PeerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeerOutput)
}

// PeerArrayInput is an input type that accepts PeerArray and PeerArrayOutput values.
// You can construct a concrete instance of `PeerArrayInput` via:
//
//	PeerArray{ PeerArgs{...} }
type PeerArrayInput interface {
	pulumi.Input

	ToPeerArrayOutput() PeerArrayOutput
	ToPeerArrayOutputWithContext(context.Context) PeerArrayOutput
}

type PeerArray []PeerInput

func (PeerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Peer)(nil)).Elem()
}

func (i PeerArray) ToPeerArrayOutput() PeerArrayOutput {
	return i.ToPeerArrayOutputWithContext(context.Background())
}

func (i PeerArray) ToPeerArrayOutputWithContext(ctx context.Context) PeerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeerArrayOutput)
}

// PeerMapInput is an input type that accepts PeerMap and PeerMapOutput values.
// You can construct a concrete instance of `PeerMapInput` via:
//
//	PeerMap{ "key": PeerArgs{...} }
type PeerMapInput interface {
	pulumi.Input

	ToPeerMapOutput() PeerMapOutput
	ToPeerMapOutputWithContext(context.Context) PeerMapOutput
}

type PeerMap map[string]PeerInput

func (PeerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Peer)(nil)).Elem()
}

func (i PeerMap) ToPeerMapOutput() PeerMapOutput {
	return i.ToPeerMapOutputWithContext(context.Background())
}

func (i PeerMap) ToPeerMapOutputWithContext(ctx context.Context) PeerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeerMapOutput)
}

type PeerOutput struct{ *pulumi.OutputState }

func (PeerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Peer)(nil)).Elem()
}

func (o PeerOutput) ToPeerOutput() PeerOutput {
	return o
}

func (o PeerOutput) ToPeerOutputWithContext(ctx context.Context) PeerOutput {
	return o
}

// Indicates whether peer needs approval
func (o PeerOutput) ApprovalRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *Peer) pulumi.BoolOutput { return v.ApprovalRequired }).(pulumi.BoolOutput)
}

// Peer city name
func (o PeerOutput) CityName() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.CityName }).(pulumi.StringOutput)
}

// Peer Connection Status
func (o PeerOutput) Connected() pulumi.BoolOutput {
	return o.ApplyT(func(v *Peer) pulumi.BoolOutput { return v.Connected }).(pulumi.BoolOutput)
}

// Peer Public IP
func (o PeerOutput) ConnectionIp() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.ConnectionIp }).(pulumi.StringOutput)
}

// Peer country code
func (o PeerOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.CountryCode }).(pulumi.StringOutput)
}

// Peer DNS Label
func (o PeerOutput) DnsLabel() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.DnsLabel }).(pulumi.StringOutput)
}

// Peer extra DNS Labels
func (o PeerOutput) ExtraDnsLabels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringArrayOutput { return v.ExtraDnsLabels }).(pulumi.StringArrayOutput)
}

// Peer Location ID
func (o PeerOutput) GeonameId() pulumi.IntOutput {
	return o.ApplyT(func(v *Peer) pulumi.IntOutput { return v.GeonameId }).(pulumi.IntOutput)
}

// Peer groups
func (o PeerOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringArrayOutput { return v.Groups }).(pulumi.StringArrayOutput)
}

// Peer's HOSTNAME
func (o PeerOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// Enable inactivity expiration for peer
func (o PeerOutput) InactivityExpirationEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Peer) pulumi.BoolOutput { return v.InactivityExpirationEnabled }).(pulumi.BoolOutput)
}

// Peer  IP
func (o PeerOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.Ip }).(pulumi.StringOutput)
}

// Peer Kernel Version
func (o PeerOutput) KernelVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.KernelVersion }).(pulumi.StringOutput)
}

// Time of peer last login
func (o PeerOutput) LastLogin() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.LastLogin }).(pulumi.StringOutput)
}

// Peer Last Seen timedate
func (o PeerOutput) LastSeen() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.LastSeen }).(pulumi.StringOutput)
}

// Indicates whether login expiration is enabled for peer
func (o PeerOutput) LoginExpirationEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Peer) pulumi.BoolOutput { return v.LoginExpirationEnabled }).(pulumi.BoolOutput)
}

// Indicates whether peer login is expired
func (o PeerOutput) LoginExpired() pulumi.BoolOutput {
	return o.ApplyT(func(v *Peer) pulumi.BoolOutput { return v.LoginExpired }).(pulumi.BoolOutput)
}

// Peer Name
func (o PeerOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Peer OS
func (o PeerOutput) Os() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.Os }).(pulumi.StringOutput)
}

// Peer ID
func (o PeerOutput) PeerId() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.PeerId }).(pulumi.StringOutput)
}

// Peer device serial number
func (o PeerOutput) SerialNumber() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.SerialNumber }).(pulumi.StringOutput)
}

// Enable SSH to Peer
func (o PeerOutput) SshEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Peer) pulumi.BoolOutput { return v.SshEnabled }).(pulumi.BoolOutput)
}

// Peer  UI Version
func (o PeerOutput) UiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.UiVersion }).(pulumi.StringOutput)
}

// User ID of peer
func (o PeerOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.UserId }).(pulumi.StringOutput)
}

// Peer  Version
func (o PeerOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *Peer) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type PeerArrayOutput struct{ *pulumi.OutputState }

func (PeerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Peer)(nil)).Elem()
}

func (o PeerArrayOutput) ToPeerArrayOutput() PeerArrayOutput {
	return o
}

func (o PeerArrayOutput) ToPeerArrayOutputWithContext(ctx context.Context) PeerArrayOutput {
	return o
}

func (o PeerArrayOutput) Index(i pulumi.IntInput) PeerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Peer {
		return vs[0].([]*Peer)[vs[1].(int)]
	}).(PeerOutput)
}

type PeerMapOutput struct{ *pulumi.OutputState }

func (PeerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Peer)(nil)).Elem()
}

func (o PeerMapOutput) ToPeerMapOutput() PeerMapOutput {
	return o
}

func (o PeerMapOutput) ToPeerMapOutputWithContext(ctx context.Context) PeerMapOutput {
	return o
}

func (o PeerMapOutput) MapIndex(k pulumi.StringInput) PeerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Peer {
		return vs[0].(map[string]*Peer)[vs[1].(string)]
	}).(PeerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PeerInput)(nil)).Elem(), &Peer{})
	pulumi.RegisterInputType(reflect.TypeOf((*PeerArrayInput)(nil)).Elem(), PeerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PeerMapInput)(nil)).Elem(), PeerMap{})
	pulumi.RegisterOutputType(PeerOutput{})
	pulumi.RegisterOutputType(PeerArrayOutput{})
	pulumi.RegisterOutputType(PeerMapOutput{})
}
