// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class NameserverGroupNameserver
    {
        /// <summary>
        /// Nameserver IP
        /// </summary>
        public readonly string Ip;
        /// <summary>
        /// Nameserver Type
        /// </summary>
        public readonly string? NsType;
        /// <summary>
        /// Nameserver Port
        /// </summary>
        public readonly int? Port;

        [OutputConstructor]
        private NameserverGroupNameserver(
            string ip,

            string? nsType,

            int? port)
        {
            Ip = ip;
            NsType = nsType;
            Port = port;
        }
    }
}
