// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PolicyRule
    {
        /// <summary>
        /// Policy Rule Action (accept|drop)
        /// </summary>
        public readonly string? Action;
        /// <summary>
        /// Policy Rule Bidirectional
        /// </summary>
        public readonly bool? Bidirectional;
        /// <summary>
        /// Policy description
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Policy Rule Destination Resource (mutually exclusive with destinations)
        /// </summary>
        public readonly Outputs.PolicyRuleDestinationResource? DestinationResource;
        /// <summary>
        /// Policy Rule Destination Groups (mutually exclusive with destination_resource)
        /// </summary>
        public readonly ImmutableArray<string> Destinations;
        /// <summary>
        /// Policy Rule Enabled
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Policy ID
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Policy Name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Policy Rule Port Ranges (mutually exclusive with ports)
        /// </summary>
        public readonly ImmutableArray<Outputs.PolicyRulePortRange> PortRanges;
        /// <summary>
        /// Policy Rule Ports (mutually exclusive with port_ranges)
        /// </summary>
        public readonly ImmutableArray<string> Ports;
        /// <summary>
        /// Policy Rule Protocol (tcp|udp|icmp|all)
        /// </summary>
        public readonly string? Protocol;
        /// <summary>
        /// Policy Rule Source Resource (mutually exclusive with sources)
        /// </summary>
        public readonly Outputs.PolicyRuleSourceResource? SourceResource;
        /// <summary>
        /// Policy Rule Source Groups (mutually exclusive with source_resource)
        /// </summary>
        public readonly ImmutableArray<string> Sources;

        [OutputConstructor]
        private PolicyRule(
            string? action,

            bool? bidirectional,

            string? description,

            Outputs.PolicyRuleDestinationResource? destinationResource,

            ImmutableArray<string> destinations,

            bool? enabled,

            string? id,

            string name,

            ImmutableArray<Outputs.PolicyRulePortRange> portRanges,

            ImmutableArray<string> ports,

            string? protocol,

            Outputs.PolicyRuleSourceResource? sourceResource,

            ImmutableArray<string> sources)
        {
            Action = action;
            Bidirectional = bidirectional;
            Description = description;
            DestinationResource = destinationResource;
            Destinations = destinations;
            Enabled = enabled;
            Id = id;
            Name = name;
            PortRanges = portRanges;
            Ports = ports;
            Protocol = protocol;
            SourceResource = sourceResource;
            Sources = sources;
        }
    }
}
