// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PolicyRuleSourceResource
    {
        public readonly string Id;
        public readonly string Type;

        [OutputConstructor]
        private PolicyRuleSourceResource(
            string id,

            string type)
        {
            Id = id;
            Type = type;
        }
    }
}
