// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PostureCheckPeerNetworkRangeCheck
    {
        public readonly string? Action;
        public readonly ImmutableArray<string> Ranges;

        [OutputConstructor]
        private PostureCheckPeerNetworkRangeCheck(
            string? action,

            ImmutableArray<string> ranges)
        {
            Action = action;
            Ranges = ranges;
        }
    }
}
