// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PostureCheckProcessCheck
    {
        public readonly string? LinuxPath;
        public readonly string? MacPath;
        public readonly string? WindowsPath;

        [OutputConstructor]
        private PostureCheckProcessCheck(
            string? linuxPath,

            string? macPath,

            string? windowsPath)
        {
            LinuxPath = linuxPath;
            MacPath = macPath;
            WindowsPath = windowsPath;
        }
    }
}
