// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PostureCheckNetbirdVersionCheck
    {
        public readonly string? MinVersion;

        [OutputConstructor]
        private PostureCheckNetbirdVersionCheck(string? minVersion)
        {
            MinVersion = minVersion;
        }
    }
}
