// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Outputs
{

    [OutputType]
    public sealed class PostureCheckOsVersionCheck
    {
        public readonly string? AndroidMinVersion;
        public readonly string? DarwinMinVersion;
        public readonly string? IosMinVersion;
        public readonly string? LinuxMinKernelVersion;
        public readonly string? WindowsMinKernelVersion;

        [OutputConstructor]
        private PostureCheckOsVersionCheck(
            string? androidMinVersion,

            string? darwinMinVersion,

            string? iosMinVersion,

            string? linuxMinKernelVersion,

            string? windowsMinKernelVersion)
        {
            AndroidMinVersion = androidMinVersion;
            DarwinMinVersion = darwinMinVersion;
            IosMinVersion = iosMinVersion;
            LinuxMinKernelVersion = linuxMinKernelVersion;
            WindowsMinKernelVersion = windowsMinKernelVersion;
        }
    }
}
