// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird;

import com.netbird.netbird.PeerArgs;
import com.netbird.netbird.Utilities;
import com.netbird.netbird.inputs.PeerState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="netbird:index/peer:Peer")
public class Peer extends com.pulumi.resources.CustomResource {
    /**
     * Indicates whether peer needs approval
     * 
     */
    @Export(name="approvalRequired", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> approvalRequired;

    /**
     * @return Indicates whether peer needs approval
     * 
     */
    public Output<Boolean> approvalRequired() {
        return this.approvalRequired;
    }
    /**
     * Peer city name
     * 
     */
    @Export(name="cityName", refs={String.class}, tree="[0]")
    private Output<String> cityName;

    /**
     * @return Peer city name
     * 
     */
    public Output<String> cityName() {
        return this.cityName;
    }
    /**
     * Peer Connection Status
     * 
     */
    @Export(name="connected", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> connected;

    /**
     * @return Peer Connection Status
     * 
     */
    public Output<Boolean> connected() {
        return this.connected;
    }
    /**
     * Peer Public IP
     * 
     */
    @Export(name="connectionIp", refs={String.class}, tree="[0]")
    private Output<String> connectionIp;

    /**
     * @return Peer Public IP
     * 
     */
    public Output<String> connectionIp() {
        return this.connectionIp;
    }
    /**
     * Peer country code
     * 
     */
    @Export(name="countryCode", refs={String.class}, tree="[0]")
    private Output<String> countryCode;

    /**
     * @return Peer country code
     * 
     */
    public Output<String> countryCode() {
        return this.countryCode;
    }
    /**
     * Peer DNS Label
     * 
     */
    @Export(name="dnsLabel", refs={String.class}, tree="[0]")
    private Output<String> dnsLabel;

    /**
     * @return Peer DNS Label
     * 
     */
    public Output<String> dnsLabel() {
        return this.dnsLabel;
    }
    /**
     * Peer extra DNS Labels
     * 
     */
    @Export(name="extraDnsLabels", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> extraDnsLabels;

    /**
     * @return Peer extra DNS Labels
     * 
     */
    public Output<List<String>> extraDnsLabels() {
        return this.extraDnsLabels;
    }
    /**
     * Peer Location ID
     * 
     */
    @Export(name="geonameId", refs={Integer.class}, tree="[0]")
    private Output<Integer> geonameId;

    /**
     * @return Peer Location ID
     * 
     */
    public Output<Integer> geonameId() {
        return this.geonameId;
    }
    /**
     * Peer groups
     * 
     */
    @Export(name="groups", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> groups;

    /**
     * @return Peer groups
     * 
     */
    public Output<List<String>> groups() {
        return this.groups;
    }
    /**
     * Peer&#39;s HOSTNAME
     * 
     */
    @Export(name="hostname", refs={String.class}, tree="[0]")
    private Output<String> hostname;

    /**
     * @return Peer&#39;s HOSTNAME
     * 
     */
    public Output<String> hostname() {
        return this.hostname;
    }
    /**
     * Enable inactivity expiration for peer
     * 
     */
    @Export(name="inactivityExpirationEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> inactivityExpirationEnabled;

    /**
     * @return Enable inactivity expiration for peer
     * 
     */
    public Output<Boolean> inactivityExpirationEnabled() {
        return this.inactivityExpirationEnabled;
    }
    /**
     * Peer  IP
     * 
     */
    @Export(name="ip", refs={String.class}, tree="[0]")
    private Output<String> ip;

    /**
     * @return Peer  IP
     * 
     */
    public Output<String> ip() {
        return this.ip;
    }
    /**
     * Peer Kernel Version
     * 
     */
    @Export(name="kernelVersion", refs={String.class}, tree="[0]")
    private Output<String> kernelVersion;

    /**
     * @return Peer Kernel Version
     * 
     */
    public Output<String> kernelVersion() {
        return this.kernelVersion;
    }
    /**
     * Time of peer last login
     * 
     */
    @Export(name="lastLogin", refs={String.class}, tree="[0]")
    private Output<String> lastLogin;

    /**
     * @return Time of peer last login
     * 
     */
    public Output<String> lastLogin() {
        return this.lastLogin;
    }
    /**
     * Peer Last Seen timedate
     * 
     */
    @Export(name="lastSeen", refs={String.class}, tree="[0]")
    private Output<String> lastSeen;

    /**
     * @return Peer Last Seen timedate
     * 
     */
    public Output<String> lastSeen() {
        return this.lastSeen;
    }
    /**
     * Indicates whether login expiration is enabled for peer
     * 
     */
    @Export(name="loginExpirationEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> loginExpirationEnabled;

    /**
     * @return Indicates whether login expiration is enabled for peer
     * 
     */
    public Output<Boolean> loginExpirationEnabled() {
        return this.loginExpirationEnabled;
    }
    /**
     * Indicates whether peer login is expired
     * 
     */
    @Export(name="loginExpired", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> loginExpired;

    /**
     * @return Indicates whether peer login is expired
     * 
     */
    public Output<Boolean> loginExpired() {
        return this.loginExpired;
    }
    /**
     * Peer Name
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Peer Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Peer OS
     * 
     */
    @Export(name="os", refs={String.class}, tree="[0]")
    private Output<String> os;

    /**
     * @return Peer OS
     * 
     */
    public Output<String> os() {
        return this.os;
    }
    /**
     * Peer ID
     * 
     */
    @Export(name="peerId", refs={String.class}, tree="[0]")
    private Output<String> peerId;

    /**
     * @return Peer ID
     * 
     */
    public Output<String> peerId() {
        return this.peerId;
    }
    /**
     * Peer device serial number
     * 
     */
    @Export(name="serialNumber", refs={String.class}, tree="[0]")
    private Output<String> serialNumber;

    /**
     * @return Peer device serial number
     * 
     */
    public Output<String> serialNumber() {
        return this.serialNumber;
    }
    /**
     * Enable SSH to Peer
     * 
     */
    @Export(name="sshEnabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> sshEnabled;

    /**
     * @return Enable SSH to Peer
     * 
     */
    public Output<Boolean> sshEnabled() {
        return this.sshEnabled;
    }
    /**
     * Peer  UI Version
     * 
     */
    @Export(name="uiVersion", refs={String.class}, tree="[0]")
    private Output<String> uiVersion;

    /**
     * @return Peer  UI Version
     * 
     */
    public Output<String> uiVersion() {
        return this.uiVersion;
    }
    /**
     * User ID of peer
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output<String> userId;

    /**
     * @return User ID of peer
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }
    /**
     * Peer  Version
     * 
     */
    @Export(name="version", refs={String.class}, tree="[0]")
    private Output<String> version;

    /**
     * @return Peer  Version
     * 
     */
    public Output<String> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Peer(java.lang.String name) {
        this(name, PeerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Peer(java.lang.String name, PeerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Peer(java.lang.String name, PeerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/peer:Peer", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Peer(java.lang.String name, Output<java.lang.String> id, @Nullable PeerState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/peer:Peer", name, state, makeResourceOptions(options, id), false);
    }

    private static PeerArgs makeArgs(PeerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PeerArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Peer get(java.lang.String name, Output<java.lang.String> id, @Nullable PeerState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Peer(name, id, state, options);
    }
}
