// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PeerArgs extends com.pulumi.resources.ResourceArgs {

    public static final PeerArgs Empty = new PeerArgs();

    /**
     * Indicates whether peer needs approval
     * 
     */
    @Import(name="approvalRequired")
    private @Nullable Output<Boolean> approvalRequired;

    /**
     * @return Indicates whether peer needs approval
     * 
     */
    public Optional<Output<Boolean>> approvalRequired() {
        return Optional.ofNullable(this.approvalRequired);
    }

    /**
     * Enable inactivity expiration for peer
     * 
     */
    @Import(name="inactivityExpirationEnabled")
    private @Nullable Output<Boolean> inactivityExpirationEnabled;

    /**
     * @return Enable inactivity expiration for peer
     * 
     */
    public Optional<Output<Boolean>> inactivityExpirationEnabled() {
        return Optional.ofNullable(this.inactivityExpirationEnabled);
    }

    /**
     * Indicates whether login expiration is enabled for peer
     * 
     */
    @Import(name="loginExpirationEnabled")
    private @Nullable Output<Boolean> loginExpirationEnabled;

    /**
     * @return Indicates whether login expiration is enabled for peer
     * 
     */
    public Optional<Output<Boolean>> loginExpirationEnabled() {
        return Optional.ofNullable(this.loginExpirationEnabled);
    }

    /**
     * Peer Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Peer Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Peer ID
     * 
     */
    @Import(name="peerId", required=true)
    private Output<String> peerId;

    /**
     * @return Peer ID
     * 
     */
    public Output<String> peerId() {
        return this.peerId;
    }

    /**
     * Enable SSH to Peer
     * 
     */
    @Import(name="sshEnabled")
    private @Nullable Output<Boolean> sshEnabled;

    /**
     * @return Enable SSH to Peer
     * 
     */
    public Optional<Output<Boolean>> sshEnabled() {
        return Optional.ofNullable(this.sshEnabled);
    }

    private PeerArgs() {}

    private PeerArgs(PeerArgs $) {
        this.approvalRequired = $.approvalRequired;
        this.inactivityExpirationEnabled = $.inactivityExpirationEnabled;
        this.loginExpirationEnabled = $.loginExpirationEnabled;
        this.name = $.name;
        this.peerId = $.peerId;
        this.sshEnabled = $.sshEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PeerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PeerArgs $;

        public Builder() {
            $ = new PeerArgs();
        }

        public Builder(PeerArgs defaults) {
            $ = new PeerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param approvalRequired Indicates whether peer needs approval
         * 
         * @return builder
         * 
         */
        public Builder approvalRequired(@Nullable Output<Boolean> approvalRequired) {
            $.approvalRequired = approvalRequired;
            return this;
        }

        /**
         * @param approvalRequired Indicates whether peer needs approval
         * 
         * @return builder
         * 
         */
        public Builder approvalRequired(Boolean approvalRequired) {
            return approvalRequired(Output.of(approvalRequired));
        }

        /**
         * @param inactivityExpirationEnabled Enable inactivity expiration for peer
         * 
         * @return builder
         * 
         */
        public Builder inactivityExpirationEnabled(@Nullable Output<Boolean> inactivityExpirationEnabled) {
            $.inactivityExpirationEnabled = inactivityExpirationEnabled;
            return this;
        }

        /**
         * @param inactivityExpirationEnabled Enable inactivity expiration for peer
         * 
         * @return builder
         * 
         */
        public Builder inactivityExpirationEnabled(Boolean inactivityExpirationEnabled) {
            return inactivityExpirationEnabled(Output.of(inactivityExpirationEnabled));
        }

        /**
         * @param loginExpirationEnabled Indicates whether login expiration is enabled for peer
         * 
         * @return builder
         * 
         */
        public Builder loginExpirationEnabled(@Nullable Output<Boolean> loginExpirationEnabled) {
            $.loginExpirationEnabled = loginExpirationEnabled;
            return this;
        }

        /**
         * @param loginExpirationEnabled Indicates whether login expiration is enabled for peer
         * 
         * @return builder
         * 
         */
        public Builder loginExpirationEnabled(Boolean loginExpirationEnabled) {
            return loginExpirationEnabled(Output.of(loginExpirationEnabled));
        }

        /**
         * @param name Peer Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Peer Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param peerId Peer ID
         * 
         * @return builder
         * 
         */
        public Builder peerId(Output<String> peerId) {
            $.peerId = peerId;
            return this;
        }

        /**
         * @param peerId Peer ID
         * 
         * @return builder
         * 
         */
        public Builder peerId(String peerId) {
            return peerId(Output.of(peerId));
        }

        /**
         * @param sshEnabled Enable SSH to Peer
         * 
         * @return builder
         * 
         */
        public Builder sshEnabled(@Nullable Output<Boolean> sshEnabled) {
            $.sshEnabled = sshEnabled;
            return this;
        }

        /**
         * @param sshEnabled Enable SSH to Peer
         * 
         * @return builder
         * 
         */
        public Builder sshEnabled(Boolean sshEnabled) {
            return sshEnabled(Output.of(sshEnabled));
        }

        public PeerArgs build() {
            if ($.peerId == null) {
                throw new MissingRequiredPropertyException("PeerArgs", "peerId");
            }
            return $;
        }
    }

}
