// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird;

import com.netbird.netbird.PersonalAccessTokenArgs;
import com.netbird.netbird.Utilities;
import com.netbird.netbird.inputs.PersonalAccessTokenState;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="netbird:index/personalAccessToken:PersonalAccessToken")
public class PersonalAccessToken extends com.pulumi.resources.CustomResource {
    /**
     * Creation timestamp
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return Creation timestamp
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * Token Expiration Date
     * 
     */
    @Export(name="expirationDate", refs={String.class}, tree="[0]")
    private Output<String> expirationDate;

    /**
     * @return Token Expiration Date
     * 
     */
    public Output<String> expirationDate() {
        return this.expirationDate;
    }
    @Export(name="expirationDays", refs={Integer.class}, tree="[0]")
    private Output<Integer> expirationDays;

    public Output<Integer> expirationDays() {
        return this.expirationDays;
    }
    /**
     * Last usage time
     * 
     */
    @Export(name="lastUsed", refs={String.class}, tree="[0]")
    private Output<String> lastUsed;

    /**
     * @return Last usage time
     * 
     */
    public Output<String> lastUsed() {
        return this.lastUsed;
    }
    /**
     * Token Name
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Token Name
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Plaintext token
     * 
     */
    @Export(name="token", refs={String.class}, tree="[0]")
    private Output<String> token;

    /**
     * @return Plaintext token
     * 
     */
    public Output<String> token() {
        return this.token;
    }
    /**
     * User ID
     * 
     */
    @Export(name="userId", refs={String.class}, tree="[0]")
    private Output<String> userId;

    /**
     * @return User ID
     * 
     */
    public Output<String> userId() {
        return this.userId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PersonalAccessToken(java.lang.String name) {
        this(name, PersonalAccessTokenArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PersonalAccessToken(java.lang.String name, PersonalAccessTokenArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PersonalAccessToken(java.lang.String name, PersonalAccessTokenArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/personalAccessToken:PersonalAccessToken", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private PersonalAccessToken(java.lang.String name, Output<java.lang.String> id, @Nullable PersonalAccessTokenState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("netbird:index/personalAccessToken:PersonalAccessToken", name, state, makeResourceOptions(options, id), false);
    }

    private static PersonalAccessTokenArgs makeArgs(PersonalAccessTokenArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PersonalAccessTokenArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "token"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PersonalAccessToken get(java.lang.String name, Output<java.lang.String> id, @Nullable PersonalAccessTokenState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PersonalAccessToken(name, id, state, options);
    }
}
