// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PeerState extends com.pulumi.resources.ResourceArgs {

    public static final PeerState Empty = new PeerState();

    /**
     * Indicates whether peer needs approval
     * 
     */
    @Import(name="approvalRequired")
    private @Nullable Output<Boolean> approvalRequired;

    /**
     * @return Indicates whether peer needs approval
     * 
     */
    public Optional<Output<Boolean>> approvalRequired() {
        return Optional.ofNullable(this.approvalRequired);
    }

    /**
     * Peer city name
     * 
     */
    @Import(name="cityName")
    private @Nullable Output<String> cityName;

    /**
     * @return Peer city name
     * 
     */
    public Optional<Output<String>> cityName() {
        return Optional.ofNullable(this.cityName);
    }

    /**
     * Peer Connection Status
     * 
     */
    @Import(name="connected")
    private @Nullable Output<Boolean> connected;

    /**
     * @return Peer Connection Status
     * 
     */
    public Optional<Output<Boolean>> connected() {
        return Optional.ofNullable(this.connected);
    }

    /**
     * Peer Public IP
     * 
     */
    @Import(name="connectionIp")
    private @Nullable Output<String> connectionIp;

    /**
     * @return Peer Public IP
     * 
     */
    public Optional<Output<String>> connectionIp() {
        return Optional.ofNullable(this.connectionIp);
    }

    /**
     * Peer country code
     * 
     */
    @Import(name="countryCode")
    private @Nullable Output<String> countryCode;

    /**
     * @return Peer country code
     * 
     */
    public Optional<Output<String>> countryCode() {
        return Optional.ofNullable(this.countryCode);
    }

    /**
     * Peer DNS Label
     * 
     */
    @Import(name="dnsLabel")
    private @Nullable Output<String> dnsLabel;

    /**
     * @return Peer DNS Label
     * 
     */
    public Optional<Output<String>> dnsLabel() {
        return Optional.ofNullable(this.dnsLabel);
    }

    /**
     * Peer extra DNS Labels
     * 
     */
    @Import(name="extraDnsLabels")
    private @Nullable Output<List<String>> extraDnsLabels;

    /**
     * @return Peer extra DNS Labels
     * 
     */
    public Optional<Output<List<String>>> extraDnsLabels() {
        return Optional.ofNullable(this.extraDnsLabels);
    }

    /**
     * Peer Location ID
     * 
     */
    @Import(name="geonameId")
    private @Nullable Output<Integer> geonameId;

    /**
     * @return Peer Location ID
     * 
     */
    public Optional<Output<Integer>> geonameId() {
        return Optional.ofNullable(this.geonameId);
    }

    /**
     * Peer groups
     * 
     */
    @Import(name="groups")
    private @Nullable Output<List<String>> groups;

    /**
     * @return Peer groups
     * 
     */
    public Optional<Output<List<String>>> groups() {
        return Optional.ofNullable(this.groups);
    }

    /**
     * Peer&#39;s HOSTNAME
     * 
     */
    @Import(name="hostname")
    private @Nullable Output<String> hostname;

    /**
     * @return Peer&#39;s HOSTNAME
     * 
     */
    public Optional<Output<String>> hostname() {
        return Optional.ofNullable(this.hostname);
    }

    /**
     * Enable inactivity expiration for peer
     * 
     */
    @Import(name="inactivityExpirationEnabled")
    private @Nullable Output<Boolean> inactivityExpirationEnabled;

    /**
     * @return Enable inactivity expiration for peer
     * 
     */
    public Optional<Output<Boolean>> inactivityExpirationEnabled() {
        return Optional.ofNullable(this.inactivityExpirationEnabled);
    }

    /**
     * Peer  IP
     * 
     */
    @Import(name="ip")
    private @Nullable Output<String> ip;

    /**
     * @return Peer  IP
     * 
     */
    public Optional<Output<String>> ip() {
        return Optional.ofNullable(this.ip);
    }

    /**
     * Peer Kernel Version
     * 
     */
    @Import(name="kernelVersion")
    private @Nullable Output<String> kernelVersion;

    /**
     * @return Peer Kernel Version
     * 
     */
    public Optional<Output<String>> kernelVersion() {
        return Optional.ofNullable(this.kernelVersion);
    }

    /**
     * Time of peer last login
     * 
     */
    @Import(name="lastLogin")
    private @Nullable Output<String> lastLogin;

    /**
     * @return Time of peer last login
     * 
     */
    public Optional<Output<String>> lastLogin() {
        return Optional.ofNullable(this.lastLogin);
    }

    /**
     * Peer Last Seen timedate
     * 
     */
    @Import(name="lastSeen")
    private @Nullable Output<String> lastSeen;

    /**
     * @return Peer Last Seen timedate
     * 
     */
    public Optional<Output<String>> lastSeen() {
        return Optional.ofNullable(this.lastSeen);
    }

    /**
     * Indicates whether login expiration is enabled for peer
     * 
     */
    @Import(name="loginExpirationEnabled")
    private @Nullable Output<Boolean> loginExpirationEnabled;

    /**
     * @return Indicates whether login expiration is enabled for peer
     * 
     */
    public Optional<Output<Boolean>> loginExpirationEnabled() {
        return Optional.ofNullable(this.loginExpirationEnabled);
    }

    /**
     * Indicates whether peer login is expired
     * 
     */
    @Import(name="loginExpired")
    private @Nullable Output<Boolean> loginExpired;

    /**
     * @return Indicates whether peer login is expired
     * 
     */
    public Optional<Output<Boolean>> loginExpired() {
        return Optional.ofNullable(this.loginExpired);
    }

    /**
     * Peer Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Peer Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Peer OS
     * 
     */
    @Import(name="os")
    private @Nullable Output<String> os;

    /**
     * @return Peer OS
     * 
     */
    public Optional<Output<String>> os() {
        return Optional.ofNullable(this.os);
    }

    /**
     * Peer ID
     * 
     */
    @Import(name="peerId")
    private @Nullable Output<String> peerId;

    /**
     * @return Peer ID
     * 
     */
    public Optional<Output<String>> peerId() {
        return Optional.ofNullable(this.peerId);
    }

    /**
     * Peer device serial number
     * 
     */
    @Import(name="serialNumber")
    private @Nullable Output<String> serialNumber;

    /**
     * @return Peer device serial number
     * 
     */
    public Optional<Output<String>> serialNumber() {
        return Optional.ofNullable(this.serialNumber);
    }

    /**
     * Enable SSH to Peer
     * 
     */
    @Import(name="sshEnabled")
    private @Nullable Output<Boolean> sshEnabled;

    /**
     * @return Enable SSH to Peer
     * 
     */
    public Optional<Output<Boolean>> sshEnabled() {
        return Optional.ofNullable(this.sshEnabled);
    }

    /**
     * Peer  UI Version
     * 
     */
    @Import(name="uiVersion")
    private @Nullable Output<String> uiVersion;

    /**
     * @return Peer  UI Version
     * 
     */
    public Optional<Output<String>> uiVersion() {
        return Optional.ofNullable(this.uiVersion);
    }

    /**
     * User ID of peer
     * 
     */
    @Import(name="userId")
    private @Nullable Output<String> userId;

    /**
     * @return User ID of peer
     * 
     */
    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    /**
     * Peer  Version
     * 
     */
    @Import(name="version")
    private @Nullable Output<String> version;

    /**
     * @return Peer  Version
     * 
     */
    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private PeerState() {}

    private PeerState(PeerState $) {
        this.approvalRequired = $.approvalRequired;
        this.cityName = $.cityName;
        this.connected = $.connected;
        this.connectionIp = $.connectionIp;
        this.countryCode = $.countryCode;
        this.dnsLabel = $.dnsLabel;
        this.extraDnsLabels = $.extraDnsLabels;
        this.geonameId = $.geonameId;
        this.groups = $.groups;
        this.hostname = $.hostname;
        this.inactivityExpirationEnabled = $.inactivityExpirationEnabled;
        this.ip = $.ip;
        this.kernelVersion = $.kernelVersion;
        this.lastLogin = $.lastLogin;
        this.lastSeen = $.lastSeen;
        this.loginExpirationEnabled = $.loginExpirationEnabled;
        this.loginExpired = $.loginExpired;
        this.name = $.name;
        this.os = $.os;
        this.peerId = $.peerId;
        this.serialNumber = $.serialNumber;
        this.sshEnabled = $.sshEnabled;
        this.uiVersion = $.uiVersion;
        this.userId = $.userId;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PeerState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PeerState $;

        public Builder() {
            $ = new PeerState();
        }

        public Builder(PeerState defaults) {
            $ = new PeerState(Objects.requireNonNull(defaults));
        }

        /**
         * @param approvalRequired Indicates whether peer needs approval
         * 
         * @return builder
         * 
         */
        public Builder approvalRequired(@Nullable Output<Boolean> approvalRequired) {
            $.approvalRequired = approvalRequired;
            return this;
        }

        /**
         * @param approvalRequired Indicates whether peer needs approval
         * 
         * @return builder
         * 
         */
        public Builder approvalRequired(Boolean approvalRequired) {
            return approvalRequired(Output.of(approvalRequired));
        }

        /**
         * @param cityName Peer city name
         * 
         * @return builder
         * 
         */
        public Builder cityName(@Nullable Output<String> cityName) {
            $.cityName = cityName;
            return this;
        }

        /**
         * @param cityName Peer city name
         * 
         * @return builder
         * 
         */
        public Builder cityName(String cityName) {
            return cityName(Output.of(cityName));
        }

        /**
         * @param connected Peer Connection Status
         * 
         * @return builder
         * 
         */
        public Builder connected(@Nullable Output<Boolean> connected) {
            $.connected = connected;
            return this;
        }

        /**
         * @param connected Peer Connection Status
         * 
         * @return builder
         * 
         */
        public Builder connected(Boolean connected) {
            return connected(Output.of(connected));
        }

        /**
         * @param connectionIp Peer Public IP
         * 
         * @return builder
         * 
         */
        public Builder connectionIp(@Nullable Output<String> connectionIp) {
            $.connectionIp = connectionIp;
            return this;
        }

        /**
         * @param connectionIp Peer Public IP
         * 
         * @return builder
         * 
         */
        public Builder connectionIp(String connectionIp) {
            return connectionIp(Output.of(connectionIp));
        }

        /**
         * @param countryCode Peer country code
         * 
         * @return builder
         * 
         */
        public Builder countryCode(@Nullable Output<String> countryCode) {
            $.countryCode = countryCode;
            return this;
        }

        /**
         * @param countryCode Peer country code
         * 
         * @return builder
         * 
         */
        public Builder countryCode(String countryCode) {
            return countryCode(Output.of(countryCode));
        }

        /**
         * @param dnsLabel Peer DNS Label
         * 
         * @return builder
         * 
         */
        public Builder dnsLabel(@Nullable Output<String> dnsLabel) {
            $.dnsLabel = dnsLabel;
            return this;
        }

        /**
         * @param dnsLabel Peer DNS Label
         * 
         * @return builder
         * 
         */
        public Builder dnsLabel(String dnsLabel) {
            return dnsLabel(Output.of(dnsLabel));
        }

        /**
         * @param extraDnsLabels Peer extra DNS Labels
         * 
         * @return builder
         * 
         */
        public Builder extraDnsLabels(@Nullable Output<List<String>> extraDnsLabels) {
            $.extraDnsLabels = extraDnsLabels;
            return this;
        }

        /**
         * @param extraDnsLabels Peer extra DNS Labels
         * 
         * @return builder
         * 
         */
        public Builder extraDnsLabels(List<String> extraDnsLabels) {
            return extraDnsLabels(Output.of(extraDnsLabels));
        }

        /**
         * @param extraDnsLabels Peer extra DNS Labels
         * 
         * @return builder
         * 
         */
        public Builder extraDnsLabels(String... extraDnsLabels) {
            return extraDnsLabels(List.of(extraDnsLabels));
        }

        /**
         * @param geonameId Peer Location ID
         * 
         * @return builder
         * 
         */
        public Builder geonameId(@Nullable Output<Integer> geonameId) {
            $.geonameId = geonameId;
            return this;
        }

        /**
         * @param geonameId Peer Location ID
         * 
         * @return builder
         * 
         */
        public Builder geonameId(Integer geonameId) {
            return geonameId(Output.of(geonameId));
        }

        /**
         * @param groups Peer groups
         * 
         * @return builder
         * 
         */
        public Builder groups(@Nullable Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        /**
         * @param groups Peer groups
         * 
         * @return builder
         * 
         */
        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        /**
         * @param groups Peer groups
         * 
         * @return builder
         * 
         */
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        /**
         * @param hostname Peer&#39;s HOSTNAME
         * 
         * @return builder
         * 
         */
        public Builder hostname(@Nullable Output<String> hostname) {
            $.hostname = hostname;
            return this;
        }

        /**
         * @param hostname Peer&#39;s HOSTNAME
         * 
         * @return builder
         * 
         */
        public Builder hostname(String hostname) {
            return hostname(Output.of(hostname));
        }

        /**
         * @param inactivityExpirationEnabled Enable inactivity expiration for peer
         * 
         * @return builder
         * 
         */
        public Builder inactivityExpirationEnabled(@Nullable Output<Boolean> inactivityExpirationEnabled) {
            $.inactivityExpirationEnabled = inactivityExpirationEnabled;
            return this;
        }

        /**
         * @param inactivityExpirationEnabled Enable inactivity expiration for peer
         * 
         * @return builder
         * 
         */
        public Builder inactivityExpirationEnabled(Boolean inactivityExpirationEnabled) {
            return inactivityExpirationEnabled(Output.of(inactivityExpirationEnabled));
        }

        /**
         * @param ip Peer  IP
         * 
         * @return builder
         * 
         */
        public Builder ip(@Nullable Output<String> ip) {
            $.ip = ip;
            return this;
        }

        /**
         * @param ip Peer  IP
         * 
         * @return builder
         * 
         */
        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        /**
         * @param kernelVersion Peer Kernel Version
         * 
         * @return builder
         * 
         */
        public Builder kernelVersion(@Nullable Output<String> kernelVersion) {
            $.kernelVersion = kernelVersion;
            return this;
        }

        /**
         * @param kernelVersion Peer Kernel Version
         * 
         * @return builder
         * 
         */
        public Builder kernelVersion(String kernelVersion) {
            return kernelVersion(Output.of(kernelVersion));
        }

        /**
         * @param lastLogin Time of peer last login
         * 
         * @return builder
         * 
         */
        public Builder lastLogin(@Nullable Output<String> lastLogin) {
            $.lastLogin = lastLogin;
            return this;
        }

        /**
         * @param lastLogin Time of peer last login
         * 
         * @return builder
         * 
         */
        public Builder lastLogin(String lastLogin) {
            return lastLogin(Output.of(lastLogin));
        }

        /**
         * @param lastSeen Peer Last Seen timedate
         * 
         * @return builder
         * 
         */
        public Builder lastSeen(@Nullable Output<String> lastSeen) {
            $.lastSeen = lastSeen;
            return this;
        }

        /**
         * @param lastSeen Peer Last Seen timedate
         * 
         * @return builder
         * 
         */
        public Builder lastSeen(String lastSeen) {
            return lastSeen(Output.of(lastSeen));
        }

        /**
         * @param loginExpirationEnabled Indicates whether login expiration is enabled for peer
         * 
         * @return builder
         * 
         */
        public Builder loginExpirationEnabled(@Nullable Output<Boolean> loginExpirationEnabled) {
            $.loginExpirationEnabled = loginExpirationEnabled;
            return this;
        }

        /**
         * @param loginExpirationEnabled Indicates whether login expiration is enabled for peer
         * 
         * @return builder
         * 
         */
        public Builder loginExpirationEnabled(Boolean loginExpirationEnabled) {
            return loginExpirationEnabled(Output.of(loginExpirationEnabled));
        }

        /**
         * @param loginExpired Indicates whether peer login is expired
         * 
         * @return builder
         * 
         */
        public Builder loginExpired(@Nullable Output<Boolean> loginExpired) {
            $.loginExpired = loginExpired;
            return this;
        }

        /**
         * @param loginExpired Indicates whether peer login is expired
         * 
         * @return builder
         * 
         */
        public Builder loginExpired(Boolean loginExpired) {
            return loginExpired(Output.of(loginExpired));
        }

        /**
         * @param name Peer Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Peer Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param os Peer OS
         * 
         * @return builder
         * 
         */
        public Builder os(@Nullable Output<String> os) {
            $.os = os;
            return this;
        }

        /**
         * @param os Peer OS
         * 
         * @return builder
         * 
         */
        public Builder os(String os) {
            return os(Output.of(os));
        }

        /**
         * @param peerId Peer ID
         * 
         * @return builder
         * 
         */
        public Builder peerId(@Nullable Output<String> peerId) {
            $.peerId = peerId;
            return this;
        }

        /**
         * @param peerId Peer ID
         * 
         * @return builder
         * 
         */
        public Builder peerId(String peerId) {
            return peerId(Output.of(peerId));
        }

        /**
         * @param serialNumber Peer device serial number
         * 
         * @return builder
         * 
         */
        public Builder serialNumber(@Nullable Output<String> serialNumber) {
            $.serialNumber = serialNumber;
            return this;
        }

        /**
         * @param serialNumber Peer device serial number
         * 
         * @return builder
         * 
         */
        public Builder serialNumber(String serialNumber) {
            return serialNumber(Output.of(serialNumber));
        }

        /**
         * @param sshEnabled Enable SSH to Peer
         * 
         * @return builder
         * 
         */
        public Builder sshEnabled(@Nullable Output<Boolean> sshEnabled) {
            $.sshEnabled = sshEnabled;
            return this;
        }

        /**
         * @param sshEnabled Enable SSH to Peer
         * 
         * @return builder
         * 
         */
        public Builder sshEnabled(Boolean sshEnabled) {
            return sshEnabled(Output.of(sshEnabled));
        }

        /**
         * @param uiVersion Peer  UI Version
         * 
         * @return builder
         * 
         */
        public Builder uiVersion(@Nullable Output<String> uiVersion) {
            $.uiVersion = uiVersion;
            return this;
        }

        /**
         * @param uiVersion Peer  UI Version
         * 
         * @return builder
         * 
         */
        public Builder uiVersion(String uiVersion) {
            return uiVersion(Output.of(uiVersion));
        }

        /**
         * @param userId User ID of peer
         * 
         * @return builder
         * 
         */
        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId User ID of peer
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        /**
         * @param version Peer  Version
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version Peer  Version
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public PeerState build() {
            return $;
        }
    }

}
