// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.netbird.netbird.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PersonalAccessTokenState extends com.pulumi.resources.ResourceArgs {

    public static final PersonalAccessTokenState Empty = new PersonalAccessTokenState();

    /**
     * Creation timestamp
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return Creation timestamp
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * Token Expiration Date
     * 
     */
    @Import(name="expirationDate")
    private @Nullable Output<String> expirationDate;

    /**
     * @return Token Expiration Date
     * 
     */
    public Optional<Output<String>> expirationDate() {
        return Optional.ofNullable(this.expirationDate);
    }

    @Import(name="expirationDays")
    private @Nullable Output<Integer> expirationDays;

    public Optional<Output<Integer>> expirationDays() {
        return Optional.ofNullable(this.expirationDays);
    }

    /**
     * Last usage time
     * 
     */
    @Import(name="lastUsed")
    private @Nullable Output<String> lastUsed;

    /**
     * @return Last usage time
     * 
     */
    public Optional<Output<String>> lastUsed() {
        return Optional.ofNullable(this.lastUsed);
    }

    /**
     * Token Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Token Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Plaintext token
     * 
     */
    @Import(name="token")
    private @Nullable Output<String> token;

    /**
     * @return Plaintext token
     * 
     */
    public Optional<Output<String>> token() {
        return Optional.ofNullable(this.token);
    }

    /**
     * User ID
     * 
     */
    @Import(name="userId")
    private @Nullable Output<String> userId;

    /**
     * @return User ID
     * 
     */
    public Optional<Output<String>> userId() {
        return Optional.ofNullable(this.userId);
    }

    private PersonalAccessTokenState() {}

    private PersonalAccessTokenState(PersonalAccessTokenState $) {
        this.createdAt = $.createdAt;
        this.expirationDate = $.expirationDate;
        this.expirationDays = $.expirationDays;
        this.lastUsed = $.lastUsed;
        this.name = $.name;
        this.token = $.token;
        this.userId = $.userId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PersonalAccessTokenState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PersonalAccessTokenState $;

        public Builder() {
            $ = new PersonalAccessTokenState();
        }

        public Builder(PersonalAccessTokenState defaults) {
            $ = new PersonalAccessTokenState(Objects.requireNonNull(defaults));
        }

        /**
         * @param createdAt Creation timestamp
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt Creation timestamp
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param expirationDate Token Expiration Date
         * 
         * @return builder
         * 
         */
        public Builder expirationDate(@Nullable Output<String> expirationDate) {
            $.expirationDate = expirationDate;
            return this;
        }

        /**
         * @param expirationDate Token Expiration Date
         * 
         * @return builder
         * 
         */
        public Builder expirationDate(String expirationDate) {
            return expirationDate(Output.of(expirationDate));
        }

        public Builder expirationDays(@Nullable Output<Integer> expirationDays) {
            $.expirationDays = expirationDays;
            return this;
        }

        public Builder expirationDays(Integer expirationDays) {
            return expirationDays(Output.of(expirationDays));
        }

        /**
         * @param lastUsed Last usage time
         * 
         * @return builder
         * 
         */
        public Builder lastUsed(@Nullable Output<String> lastUsed) {
            $.lastUsed = lastUsed;
            return this;
        }

        /**
         * @param lastUsed Last usage time
         * 
         * @return builder
         * 
         */
        public Builder lastUsed(String lastUsed) {
            return lastUsed(Output.of(lastUsed));
        }

        /**
         * @param name Token Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Token Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param token Plaintext token
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token Plaintext token
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        /**
         * @param userId User ID
         * 
         * @return builder
         * 
         */
        public Builder userId(@Nullable Output<String> userId) {
            $.userId = userId;
            return this;
        }

        /**
         * @param userId User ID
         * 
         * @return builder
         * 
         */
        public Builder userId(String userId) {
            return userId(Output.of(userId));
        }

        public PersonalAccessTokenState build() {
            return $;
        }
    }

}
