// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/accountSettings:AccountSettings")]
    public partial class AccountSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Allows propagate the new user auto groups to peers that belongs to the user
        /// </summary>
        [Output("groupsPropagationEnabled")]
        public Output<bool> GroupsPropagationEnabled { get; private set; } = null!;

        /// <summary>
        /// List of groups to which users are allowed access
        /// </summary>
        [Output("jwtAllowGroups")]
        public Output<ImmutableArray<string>> JwtAllowGroups { get; private set; } = null!;

        /// <summary>
        /// Name of the claim from which we extract groups names to add it to account groups.
        /// </summary>
        [Output("jwtGroupsClaimName")]
        public Output<string> JwtGroupsClaimName { get; private set; } = null!;

        /// <summary>
        /// Allows extract groups from JWT claim and add it to account groups.
        /// </summary>
        [Output("jwtGroupsEnabled")]
        public Output<bool> JwtGroupsEnabled { get; private set; } = null!;

        /// <summary>
        /// Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
        /// </summary>
        [Output("networkTrafficLogsEnabled")]
        public Output<bool> NetworkTrafficLogsEnabled { get; private set; } = null!;

        /// <summary>
        /// Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
        /// </summary>
        [Output("networkTrafficPacketCounterEnabled")]
        public Output<bool> NetworkTrafficPacketCounterEnabled { get; private set; } = null!;

        /// <summary>
        /// (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
        /// </summary>
        [Output("peerApprovalEnabled")]
        public Output<bool> PeerApprovalEnabled { get; private set; } = null!;

        /// <summary>
        /// Period of time of inactivity after which peer session expires (seconds).
        /// </summary>
        [Output("peerInactivityExpiration")]
        public Output<int> PeerInactivityExpiration { get; private set; } = null!;

        /// <summary>
        /// Enables or disables peer inactivity expiration globally. After peer's session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
        /// </summary>
        [Output("peerInactivityExpirationEnabled")]
        public Output<bool> PeerInactivityExpirationEnabled { get; private set; } = null!;

        /// <summary>
        /// Period of time after which peer login expires (seconds).
        /// </summary>
        [Output("peerLoginExpiration")]
        public Output<int> PeerLoginExpiration { get; private set; } = null!;

        /// <summary>
        /// Enables or disables peer login expiration globally. After peer's login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
        /// </summary>
        [Output("peerLoginExpirationEnabled")]
        public Output<bool> PeerLoginExpirationEnabled { get; private set; } = null!;

        /// <summary>
        /// Allows blocking regular users from viewing parts of the system.
        /// </summary>
        [Output("regularUsersViewBlocked")]
        public Output<bool> RegularUsersViewBlocked { get; private set; } = null!;

        /// <summary>
        /// Enables or disables DNS resolution on the routing peers
        /// </summary>
        [Output("routingPeerDnsResolutionEnabled")]
        public Output<bool> RoutingPeerDnsResolutionEnabled { get; private set; } = null!;


        /// <summary>
        /// Create a AccountSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AccountSettings(string name, AccountSettingsArgs? args = null, CustomResourceOptions? options = null)
            : base("netbird:index/accountSettings:AccountSettings", name, args ?? new AccountSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AccountSettings(string name, Input<string> id, AccountSettingsState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/accountSettings:AccountSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AccountSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AccountSettings Get(string name, Input<string> id, AccountSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new AccountSettings(name, id, state, options);
        }
    }

    public sealed class AccountSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows propagate the new user auto groups to peers that belongs to the user
        /// </summary>
        [Input("groupsPropagationEnabled")]
        public Input<bool>? GroupsPropagationEnabled { get; set; }

        [Input("jwtAllowGroups")]
        private InputList<string>? _jwtAllowGroups;

        /// <summary>
        /// List of groups to which users are allowed access
        /// </summary>
        public InputList<string> JwtAllowGroups
        {
            get => _jwtAllowGroups ?? (_jwtAllowGroups = new InputList<string>());
            set => _jwtAllowGroups = value;
        }

        /// <summary>
        /// Name of the claim from which we extract groups names to add it to account groups.
        /// </summary>
        [Input("jwtGroupsClaimName")]
        public Input<string>? JwtGroupsClaimName { get; set; }

        /// <summary>
        /// Allows extract groups from JWT claim and add it to account groups.
        /// </summary>
        [Input("jwtGroupsEnabled")]
        public Input<bool>? JwtGroupsEnabled { get; set; }

        /// <summary>
        /// Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
        /// </summary>
        [Input("networkTrafficLogsEnabled")]
        public Input<bool>? NetworkTrafficLogsEnabled { get; set; }

        /// <summary>
        /// Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
        /// </summary>
        [Input("networkTrafficPacketCounterEnabled")]
        public Input<bool>? NetworkTrafficPacketCounterEnabled { get; set; }

        /// <summary>
        /// (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
        /// </summary>
        [Input("peerApprovalEnabled")]
        public Input<bool>? PeerApprovalEnabled { get; set; }

        /// <summary>
        /// Period of time of inactivity after which peer session expires (seconds).
        /// </summary>
        [Input("peerInactivityExpiration")]
        public Input<int>? PeerInactivityExpiration { get; set; }

        /// <summary>
        /// Enables or disables peer inactivity expiration globally. After peer's session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
        /// </summary>
        [Input("peerInactivityExpirationEnabled")]
        public Input<bool>? PeerInactivityExpirationEnabled { get; set; }

        /// <summary>
        /// Period of time after which peer login expires (seconds).
        /// </summary>
        [Input("peerLoginExpiration")]
        public Input<int>? PeerLoginExpiration { get; set; }

        /// <summary>
        /// Enables or disables peer login expiration globally. After peer's login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
        /// </summary>
        [Input("peerLoginExpirationEnabled")]
        public Input<bool>? PeerLoginExpirationEnabled { get; set; }

        /// <summary>
        /// Allows blocking regular users from viewing parts of the system.
        /// </summary>
        [Input("regularUsersViewBlocked")]
        public Input<bool>? RegularUsersViewBlocked { get; set; }

        /// <summary>
        /// Enables or disables DNS resolution on the routing peers
        /// </summary>
        [Input("routingPeerDnsResolutionEnabled")]
        public Input<bool>? RoutingPeerDnsResolutionEnabled { get; set; }

        public AccountSettingsArgs()
        {
        }
        public static new AccountSettingsArgs Empty => new AccountSettingsArgs();
    }

    public sealed class AccountSettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows propagate the new user auto groups to peers that belongs to the user
        /// </summary>
        [Input("groupsPropagationEnabled")]
        public Input<bool>? GroupsPropagationEnabled { get; set; }

        [Input("jwtAllowGroups")]
        private InputList<string>? _jwtAllowGroups;

        /// <summary>
        /// List of groups to which users are allowed access
        /// </summary>
        public InputList<string> JwtAllowGroups
        {
            get => _jwtAllowGroups ?? (_jwtAllowGroups = new InputList<string>());
            set => _jwtAllowGroups = value;
        }

        /// <summary>
        /// Name of the claim from which we extract groups names to add it to account groups.
        /// </summary>
        [Input("jwtGroupsClaimName")]
        public Input<string>? JwtGroupsClaimName { get; set; }

        /// <summary>
        /// Allows extract groups from JWT claim and add it to account groups.
        /// </summary>
        [Input("jwtGroupsEnabled")]
        public Input<bool>? JwtGroupsEnabled { get; set; }

        /// <summary>
        /// Enables or disables network traffic logging. If enabled, all network traffic events from peers will be stored.
        /// </summary>
        [Input("networkTrafficLogsEnabled")]
        public Input<bool>? NetworkTrafficLogsEnabled { get; set; }

        /// <summary>
        /// Enables or disables network traffic packet counter. If enabled, network packets and their size will be counted and reported. (This can have an slight impact on performance)
        /// </summary>
        [Input("networkTrafficPacketCounterEnabled")]
        public Input<bool>? NetworkTrafficPacketCounterEnabled { get; set; }

        /// <summary>
        /// (Cloud only) Enables or disables peer approval globally. If enabled, all peers added will be in pending state until approved by an admin.
        /// </summary>
        [Input("peerApprovalEnabled")]
        public Input<bool>? PeerApprovalEnabled { get; set; }

        /// <summary>
        /// Period of time of inactivity after which peer session expires (seconds).
        /// </summary>
        [Input("peerInactivityExpiration")]
        public Input<int>? PeerInactivityExpiration { get; set; }

        /// <summary>
        /// Enables or disables peer inactivity expiration globally. After peer's session has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
        /// </summary>
        [Input("peerInactivityExpirationEnabled")]
        public Input<bool>? PeerInactivityExpirationEnabled { get; set; }

        /// <summary>
        /// Period of time after which peer login expires (seconds).
        /// </summary>
        [Input("peerLoginExpiration")]
        public Input<int>? PeerLoginExpiration { get; set; }

        /// <summary>
        /// Enables or disables peer login expiration globally. After peer's login has expired the user has to log in (authenticate). Applies only to peers that were added by a user (interactive SSO login).
        /// </summary>
        [Input("peerLoginExpirationEnabled")]
        public Input<bool>? PeerLoginExpirationEnabled { get; set; }

        /// <summary>
        /// Allows blocking regular users from viewing parts of the system.
        /// </summary>
        [Input("regularUsersViewBlocked")]
        public Input<bool>? RegularUsersViewBlocked { get; set; }

        /// <summary>
        /// Enables or disables DNS resolution on the routing peers
        /// </summary>
        [Input("routingPeerDnsResolutionEnabled")]
        public Input<bool>? RoutingPeerDnsResolutionEnabled { get; set; }

        public AccountSettingsState()
        {
        }
        public static new AccountSettingsState Empty => new AccountSettingsState();
    }
}
