// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/dnsSettings:DnsSettings")]
    public partial class DnsSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Groups whose DNS management is disabled
        /// </summary>
        [Output("disabledManagementGroups")]
        public Output<ImmutableArray<string>> DisabledManagementGroups { get; private set; } = null!;


        /// <summary>
        /// Create a DnsSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DnsSettings(string name, DnsSettingsArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/dnsSettings:DnsSettings", name, args ?? new DnsSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DnsSettings(string name, Input<string> id, DnsSettingsState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/dnsSettings:DnsSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DnsSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DnsSettings Get(string name, Input<string> id, DnsSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new DnsSettings(name, id, state, options);
        }
    }

    public sealed class DnsSettingsArgs : global::Pulumi.ResourceArgs
    {
        [Input("disabledManagementGroups", required: true)]
        private InputList<string>? _disabledManagementGroups;

        /// <summary>
        /// Groups whose DNS management is disabled
        /// </summary>
        public InputList<string> DisabledManagementGroups
        {
            get => _disabledManagementGroups ?? (_disabledManagementGroups = new InputList<string>());
            set => _disabledManagementGroups = value;
        }

        public DnsSettingsArgs()
        {
        }
        public static new DnsSettingsArgs Empty => new DnsSettingsArgs();
    }

    public sealed class DnsSettingsState : global::Pulumi.ResourceArgs
    {
        [Input("disabledManagementGroups")]
        private InputList<string>? _disabledManagementGroups;

        /// <summary>
        /// Groups whose DNS management is disabled
        /// </summary>
        public InputList<string> DisabledManagementGroups
        {
            get => _disabledManagementGroups ?? (_disabledManagementGroups = new InputList<string>());
            set => _disabledManagementGroups = value;
        }

        public DnsSettingsState()
        {
        }
        public static new DnsSettingsState Empty => new DnsSettingsState();
    }
}
