// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetAccountSettings
    {
        public static Task<GetAccountSettingsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountSettingsResult>("netbird:index/getAccountSettings:getAccountSettings", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetAccountSettingsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountSettingsResult>("netbird:index/getAccountSettings:getAccountSettings", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetAccountSettingsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountSettingsResult>("netbird:index/getAccountSettings:getAccountSettings", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetAccountSettingsResult
    {
        public readonly bool GroupsPropagationEnabled;
        public readonly string Id;
        public readonly ImmutableArray<string> JwtAllowGroups;
        public readonly string JwtGroupsClaimName;
        public readonly bool JwtGroupsEnabled;
        public readonly bool NetworkTrafficLogsEnabled;
        public readonly bool NetworkTrafficPacketCounterEnabled;
        public readonly bool PeerApprovalEnabled;
        public readonly int PeerInactivityExpiration;
        public readonly bool PeerInactivityExpirationEnabled;
        public readonly int PeerLoginExpiration;
        public readonly bool PeerLoginExpirationEnabled;
        public readonly bool RegularUsersViewBlocked;
        public readonly bool RoutingPeerDnsResolutionEnabled;

        [OutputConstructor]
        private GetAccountSettingsResult(
            bool groupsPropagationEnabled,

            string id,

            ImmutableArray<string> jwtAllowGroups,

            string jwtGroupsClaimName,

            bool jwtGroupsEnabled,

            bool networkTrafficLogsEnabled,

            bool networkTrafficPacketCounterEnabled,

            bool peerApprovalEnabled,

            int peerInactivityExpiration,

            bool peerInactivityExpirationEnabled,

            int peerLoginExpiration,

            bool peerLoginExpirationEnabled,

            bool regularUsersViewBlocked,

            bool routingPeerDnsResolutionEnabled)
        {
            GroupsPropagationEnabled = groupsPropagationEnabled;
            Id = id;
            JwtAllowGroups = jwtAllowGroups;
            JwtGroupsClaimName = jwtGroupsClaimName;
            JwtGroupsEnabled = jwtGroupsEnabled;
            NetworkTrafficLogsEnabled = networkTrafficLogsEnabled;
            NetworkTrafficPacketCounterEnabled = networkTrafficPacketCounterEnabled;
            PeerApprovalEnabled = peerApprovalEnabled;
            PeerInactivityExpiration = peerInactivityExpiration;
            PeerInactivityExpirationEnabled = peerInactivityExpirationEnabled;
            PeerLoginExpiration = peerLoginExpiration;
            PeerLoginExpirationEnabled = peerLoginExpirationEnabled;
            RegularUsersViewBlocked = regularUsersViewBlocked;
            RoutingPeerDnsResolutionEnabled = routingPeerDnsResolutionEnabled;
        }
    }
}
