// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetDnsSettings
    {
        public static Task<GetDnsSettingsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDnsSettingsResult>("netbird:index/getDnsSettings:getDnsSettings", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetDnsSettingsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDnsSettingsResult>("netbird:index/getDnsSettings:getDnsSettings", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetDnsSettingsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDnsSettingsResult>("netbird:index/getDnsSettings:getDnsSettings", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetDnsSettingsResult
    {
        public readonly ImmutableArray<string> DisabledManagementGroups;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetDnsSettingsResult(
            ImmutableArray<string> disabledManagementGroups,

            string id)
        {
            DisabledManagementGroups = disabledManagementGroups;
            Id = id;
        }
    }
}
