// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetNetworkResource
    {
        public static Task<GetNetworkResourceResult> InvokeAsync(GetNetworkResourceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworkResourceResult>("netbird:index/getNetworkResource:getNetworkResource", args ?? new GetNetworkResourceArgs(), options.WithDefaults());

        public static Output<GetNetworkResourceResult> Invoke(GetNetworkResourceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkResourceResult>("netbird:index/getNetworkResource:getNetworkResource", args ?? new GetNetworkResourceInvokeArgs(), options.WithDefaults());

        public static Output<GetNetworkResourceResult> Invoke(GetNetworkResourceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkResourceResult>("netbird:index/getNetworkResource:getNetworkResource", args ?? new GetNetworkResourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkResourceArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("networkId", required: true)]
        public string NetworkId { get; set; } = null!;

        public GetNetworkResourceArgs()
        {
        }
        public static new GetNetworkResourceArgs Empty => new GetNetworkResourceArgs();
    }

    public sealed class GetNetworkResourceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        public GetNetworkResourceInvokeArgs()
        {
        }
        public static new GetNetworkResourceInvokeArgs Empty => new GetNetworkResourceInvokeArgs();
    }


    [OutputType]
    public sealed class GetNetworkResourceResult
    {
        public readonly string Address;
        public readonly string Description;
        public readonly bool Enabled;
        public readonly ImmutableArray<string> Groups;
        public readonly string Id;
        public readonly string Name;
        public readonly string NetworkId;

        [OutputConstructor]
        private GetNetworkResourceResult(
            string address,

            string description,

            bool enabled,

            ImmutableArray<string> groups,

            string id,

            string name,

            string networkId)
        {
            Address = address;
            Description = description;
            Enabled = enabled;
            Groups = groups;
            Id = id;
            Name = name;
            NetworkId = networkId;
        }
    }
}
