// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetNameserverGroup
    {
        public static Task<GetNameserverGroupResult> InvokeAsync(GetNameserverGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNameserverGroupResult>("netbird:index/getNameserverGroup:getNameserverGroup", args ?? new GetNameserverGroupArgs(), options.WithDefaults());

        public static Output<GetNameserverGroupResult> Invoke(GetNameserverGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNameserverGroupResult>("netbird:index/getNameserverGroup:getNameserverGroup", args ?? new GetNameserverGroupInvokeArgs(), options.WithDefaults());

        public static Output<GetNameserverGroupResult> Invoke(GetNameserverGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNameserverGroupResult>("netbird:index/getNameserverGroup:getNameserverGroup", args ?? new GetNameserverGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNameserverGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetNameserverGroupArgs()
        {
        }
        public static new GetNameserverGroupArgs Empty => new GetNameserverGroupArgs();
    }

    public sealed class GetNameserverGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetNameserverGroupInvokeArgs()
        {
        }
        public static new GetNameserverGroupInvokeArgs Empty => new GetNameserverGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetNameserverGroupResult
    {
        public readonly string Description;
        public readonly ImmutableArray<string> Domains;
        public readonly bool Enabled;
        public readonly ImmutableArray<string> Groups;
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetNameserverGroupNameserverResult> Nameservers;
        public readonly bool Primary;
        public readonly bool SearchDomainsEnabled;

        [OutputConstructor]
        private GetNameserverGroupResult(
            string description,

            ImmutableArray<string> domains,

            bool enabled,

            ImmutableArray<string> groups,

            string id,

            string name,

            ImmutableArray<Outputs.GetNameserverGroupNameserverResult> nameservers,

            bool primary,

            bool searchDomainsEnabled)
        {
            Description = description;
            Domains = domains;
            Enabled = enabled;
            Groups = groups;
            Id = id;
            Name = name;
            Nameservers = nameservers;
            Primary = primary;
            SearchDomainsEnabled = searchDomainsEnabled;
        }
    }
}
