// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetNetworkRouter
    {
        public static Task<GetNetworkRouterResult> InvokeAsync(GetNetworkRouterArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworkRouterResult>("netbird:index/getNetworkRouter:getNetworkRouter", args ?? new GetNetworkRouterArgs(), options.WithDefaults());

        public static Output<GetNetworkRouterResult> Invoke(GetNetworkRouterInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkRouterResult>("netbird:index/getNetworkRouter:getNetworkRouter", args ?? new GetNetworkRouterInvokeArgs(), options.WithDefaults());

        public static Output<GetNetworkRouterResult> Invoke(GetNetworkRouterInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkRouterResult>("netbird:index/getNetworkRouter:getNetworkRouter", args ?? new GetNetworkRouterInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkRouterArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("networkId", required: true)]
        public string NetworkId { get; set; } = null!;

        public GetNetworkRouterArgs()
        {
        }
        public static new GetNetworkRouterArgs Empty => new GetNetworkRouterArgs();
    }

    public sealed class GetNetworkRouterInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        public GetNetworkRouterInvokeArgs()
        {
        }
        public static new GetNetworkRouterInvokeArgs Empty => new GetNetworkRouterInvokeArgs();
    }


    [OutputType]
    public sealed class GetNetworkRouterResult
    {
        public readonly bool Enabled;
        public readonly string Id;
        public readonly bool Masquerade;
        public readonly int Metric;
        public readonly string NetworkId;
        public readonly string Peer;
        public readonly ImmutableArray<string> PeerGroups;

        [OutputConstructor]
        private GetNetworkRouterResult(
            bool enabled,

            string id,

            bool masquerade,

            int metric,

            string networkId,

            string peer,

            ImmutableArray<string> peerGroups)
        {
            Enabled = enabled;
            Id = id;
            Masquerade = masquerade;
            Metric = metric;
            NetworkId = networkId;
            Peer = peer;
            PeerGroups = peerGroups;
        }
    }
}
