// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetPeers
    {
        public static Task<GetPeersResult> InvokeAsync(GetPeersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPeersResult>("netbird:index/getPeers:getPeers", args ?? new GetPeersArgs(), options.WithDefaults());

        public static Output<GetPeersResult> Invoke(GetPeersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPeersResult>("netbird:index/getPeers:getPeers", args ?? new GetPeersInvokeArgs(), options.WithDefaults());

        public static Output<GetPeersResult> Invoke(GetPeersInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPeersResult>("netbird:index/getPeers:getPeers", args ?? new GetPeersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPeersArgs : global::Pulumi.InvokeArgs
    {
        [Input("approvalRequired")]
        public bool? ApprovalRequired { get; set; }

        [Input("cityName")]
        public string? CityName { get; set; }

        [Input("connected")]
        public bool? Connected { get; set; }

        [Input("connectionIp")]
        public string? ConnectionIp { get; set; }

        [Input("countryCode")]
        public string? CountryCode { get; set; }

        [Input("dnsLabel")]
        public string? DnsLabel { get; set; }

        [Input("extraDnsLabels")]
        private List<string>? _extraDnsLabels;
        public List<string> ExtraDnsLabels
        {
            get => _extraDnsLabels ?? (_extraDnsLabels = new List<string>());
            set => _extraDnsLabels = value;
        }

        [Input("geonameId")]
        public int? GeonameId { get; set; }

        [Input("groups")]
        private List<string>? _groups;
        public List<string> Groups
        {
            get => _groups ?? (_groups = new List<string>());
            set => _groups = value;
        }

        [Input("hostname")]
        public string? Hostname { get; set; }

        [Input("inactivityExpirationEnabled")]
        public bool? InactivityExpirationEnabled { get; set; }

        [Input("ip")]
        public string? Ip { get; set; }

        [Input("loginExpirationEnabled")]
        public bool? LoginExpirationEnabled { get; set; }

        [Input("loginExpired")]
        public bool? LoginExpired { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("os")]
        public string? Os { get; set; }

        [Input("sshEnabled")]
        public bool? SshEnabled { get; set; }

        [Input("userId")]
        public string? UserId { get; set; }

        public GetPeersArgs()
        {
        }
        public static new GetPeersArgs Empty => new GetPeersArgs();
    }

    public sealed class GetPeersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("approvalRequired")]
        public Input<bool>? ApprovalRequired { get; set; }

        [Input("cityName")]
        public Input<string>? CityName { get; set; }

        [Input("connected")]
        public Input<bool>? Connected { get; set; }

        [Input("connectionIp")]
        public Input<string>? ConnectionIp { get; set; }

        [Input("countryCode")]
        public Input<string>? CountryCode { get; set; }

        [Input("dnsLabel")]
        public Input<string>? DnsLabel { get; set; }

        [Input("extraDnsLabels")]
        private InputList<string>? _extraDnsLabels;
        public InputList<string> ExtraDnsLabels
        {
            get => _extraDnsLabels ?? (_extraDnsLabels = new InputList<string>());
            set => _extraDnsLabels = value;
        }

        [Input("geonameId")]
        public Input<int>? GeonameId { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        [Input("inactivityExpirationEnabled")]
        public Input<bool>? InactivityExpirationEnabled { get; set; }

        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("loginExpirationEnabled")]
        public Input<bool>? LoginExpirationEnabled { get; set; }

        [Input("loginExpired")]
        public Input<bool>? LoginExpired { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("os")]
        public Input<string>? Os { get; set; }

        [Input("sshEnabled")]
        public Input<bool>? SshEnabled { get; set; }

        [Input("userId")]
        public Input<string>? UserId { get; set; }

        public GetPeersInvokeArgs()
        {
        }
        public static new GetPeersInvokeArgs Empty => new GetPeersInvokeArgs();
    }


    [OutputType]
    public sealed class GetPeersResult
    {
        public readonly bool ApprovalRequired;
        public readonly string CityName;
        public readonly bool Connected;
        public readonly string ConnectionIp;
        public readonly string CountryCode;
        public readonly string DnsLabel;
        public readonly ImmutableArray<string> ExtraDnsLabels;
        public readonly int GeonameId;
        public readonly ImmutableArray<string> Groups;
        public readonly string Hostname;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly bool InactivityExpirationEnabled;
        public readonly string Ip;
        public readonly string KernelVersion;
        public readonly string LastLogin;
        public readonly string LastSeen;
        public readonly bool LoginExpirationEnabled;
        public readonly bool LoginExpired;
        public readonly string Name;
        public readonly string Os;
        public readonly string SerialNumber;
        public readonly bool SshEnabled;
        public readonly string UiVersion;
        public readonly string UserId;
        public readonly string Version;

        [OutputConstructor]
        private GetPeersResult(
            bool approvalRequired,

            string cityName,

            bool connected,

            string connectionIp,

            string countryCode,

            string dnsLabel,

            ImmutableArray<string> extraDnsLabels,

            int geonameId,

            ImmutableArray<string> groups,

            string hostname,

            string id,

            ImmutableArray<string> ids,

            bool inactivityExpirationEnabled,

            string ip,

            string kernelVersion,

            string lastLogin,

            string lastSeen,

            bool loginExpirationEnabled,

            bool loginExpired,

            string name,

            string os,

            string serialNumber,

            bool sshEnabled,

            string uiVersion,

            string userId,

            string version)
        {
            ApprovalRequired = approvalRequired;
            CityName = cityName;
            Connected = connected;
            ConnectionIp = connectionIp;
            CountryCode = countryCode;
            DnsLabel = dnsLabel;
            ExtraDnsLabels = extraDnsLabels;
            GeonameId = geonameId;
            Groups = groups;
            Hostname = hostname;
            Id = id;
            Ids = ids;
            InactivityExpirationEnabled = inactivityExpirationEnabled;
            Ip = ip;
            KernelVersion = kernelVersion;
            LastLogin = lastLogin;
            LastSeen = lastSeen;
            LoginExpirationEnabled = loginExpirationEnabled;
            LoginExpired = loginExpired;
            Name = name;
            Os = os;
            SerialNumber = serialNumber;
            SshEnabled = sshEnabled;
            UiVersion = uiVersion;
            UserId = userId;
            Version = version;
        }
    }
}
