// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetPostureCheck
    {
        public static Task<GetPostureCheckResult> InvokeAsync(GetPostureCheckArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPostureCheckResult>("netbird:index/getPostureCheck:getPostureCheck", args ?? new GetPostureCheckArgs(), options.WithDefaults());

        public static Output<GetPostureCheckResult> Invoke(GetPostureCheckInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPostureCheckResult>("netbird:index/getPostureCheck:getPostureCheck", args ?? new GetPostureCheckInvokeArgs(), options.WithDefaults());

        public static Output<GetPostureCheckResult> Invoke(GetPostureCheckInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPostureCheckResult>("netbird:index/getPostureCheck:getPostureCheck", args ?? new GetPostureCheckInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPostureCheckArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetPostureCheckArgs()
        {
        }
        public static new GetPostureCheckArgs Empty => new GetPostureCheckArgs();
    }

    public sealed class GetPostureCheckInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetPostureCheckInvokeArgs()
        {
        }
        public static new GetPostureCheckInvokeArgs Empty => new GetPostureCheckInvokeArgs();
    }


    [OutputType]
    public sealed class GetPostureCheckResult
    {
        public readonly string Description;
        public readonly Outputs.GetPostureCheckGeoLocationCheckResult GeoLocationCheck;
        public readonly string Id;
        public readonly string Name;
        public readonly Outputs.GetPostureCheckNetbirdVersionCheckResult NetbirdVersionCheck;
        public readonly Outputs.GetPostureCheckOsVersionCheckResult OsVersionCheck;
        public readonly Outputs.GetPostureCheckPeerNetworkRangeCheckResult PeerNetworkRangeCheck;
        public readonly ImmutableArray<Outputs.GetPostureCheckProcessCheckResult> ProcessChecks;

        [OutputConstructor]
        private GetPostureCheckResult(
            string description,

            Outputs.GetPostureCheckGeoLocationCheckResult geoLocationCheck,

            string id,

            string name,

            Outputs.GetPostureCheckNetbirdVersionCheckResult netbirdVersionCheck,

            Outputs.GetPostureCheckOsVersionCheckResult osVersionCheck,

            Outputs.GetPostureCheckPeerNetworkRangeCheckResult peerNetworkRangeCheck,

            ImmutableArray<Outputs.GetPostureCheckProcessCheckResult> processChecks)
        {
            Description = description;
            GeoLocationCheck = geoLocationCheck;
            Id = id;
            Name = name;
            NetbirdVersionCheck = netbirdVersionCheck;
            OsVersionCheck = osVersionCheck;
            PeerNetworkRangeCheck = peerNetworkRangeCheck;
            ProcessChecks = processChecks;
        }
    }
}
