// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetPeer
    {
        public static Task<GetPeerResult> InvokeAsync(GetPeerArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPeerResult>("netbird:index/getPeer:getPeer", args ?? new GetPeerArgs(), options.WithDefaults());

        public static Output<GetPeerResult> Invoke(GetPeerInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPeerResult>("netbird:index/getPeer:getPeer", args ?? new GetPeerInvokeArgs(), options.WithDefaults());

        public static Output<GetPeerResult> Invoke(GetPeerInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPeerResult>("netbird:index/getPeer:getPeer", args ?? new GetPeerInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPeerArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("ip")]
        public string? Ip { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetPeerArgs()
        {
        }
        public static new GetPeerArgs Empty => new GetPeerArgs();
    }

    public sealed class GetPeerInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetPeerInvokeArgs()
        {
        }
        public static new GetPeerInvokeArgs Empty => new GetPeerInvokeArgs();
    }


    [OutputType]
    public sealed class GetPeerResult
    {
        public readonly bool ApprovalRequired;
        public readonly string CityName;
        public readonly bool Connected;
        public readonly string ConnectionIp;
        public readonly string CountryCode;
        public readonly string DnsLabel;
        public readonly ImmutableArray<string> ExtraDnsLabels;
        public readonly int GeonameId;
        public readonly ImmutableArray<string> Groups;
        public readonly string Hostname;
        public readonly string Id;
        public readonly bool InactivityExpirationEnabled;
        public readonly string Ip;
        public readonly string KernelVersion;
        public readonly string LastLogin;
        public readonly string LastSeen;
        public readonly bool LoginExpirationEnabled;
        public readonly bool LoginExpired;
        public readonly string Name;
        public readonly string Os;
        public readonly string SerialNumber;
        public readonly bool SshEnabled;
        public readonly string UiVersion;
        public readonly string UserId;
        public readonly string Version;

        [OutputConstructor]
        private GetPeerResult(
            bool approvalRequired,

            string cityName,

            bool connected,

            string connectionIp,

            string countryCode,

            string dnsLabel,

            ImmutableArray<string> extraDnsLabels,

            int geonameId,

            ImmutableArray<string> groups,

            string hostname,

            string id,

            bool inactivityExpirationEnabled,

            string ip,

            string kernelVersion,

            string lastLogin,

            string lastSeen,

            bool loginExpirationEnabled,

            bool loginExpired,

            string name,

            string os,

            string serialNumber,

            bool sshEnabled,

            string uiVersion,

            string userId,

            string version)
        {
            ApprovalRequired = approvalRequired;
            CityName = cityName;
            Connected = connected;
            ConnectionIp = connectionIp;
            CountryCode = countryCode;
            DnsLabel = dnsLabel;
            ExtraDnsLabels = extraDnsLabels;
            GeonameId = geonameId;
            Groups = groups;
            Hostname = hostname;
            Id = id;
            InactivityExpirationEnabled = inactivityExpirationEnabled;
            Ip = ip;
            KernelVersion = kernelVersion;
            LastLogin = lastLogin;
            LastSeen = lastSeen;
            LoginExpirationEnabled = loginExpirationEnabled;
            LoginExpired = loginExpired;
            Name = name;
            Os = os;
            SerialNumber = serialNumber;
            SshEnabled = sshEnabled;
            UiVersion = uiVersion;
            UserId = userId;
            Version = version;
        }
    }
}
