// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetPolicy
    {
        public static Task<GetPolicyResult> InvokeAsync(GetPolicyArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPolicyResult>("netbird:index/getPolicy:getPolicy", args ?? new GetPolicyArgs(), options.WithDefaults());

        public static Output<GetPolicyResult> Invoke(GetPolicyInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPolicyResult>("netbird:index/getPolicy:getPolicy", args ?? new GetPolicyInvokeArgs(), options.WithDefaults());

        public static Output<GetPolicyResult> Invoke(GetPolicyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPolicyResult>("netbird:index/getPolicy:getPolicy", args ?? new GetPolicyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPolicyArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("rules")]
        private List<Inputs.GetPolicyRuleArgs>? _rules;
        public List<Inputs.GetPolicyRuleArgs> Rules
        {
            get => _rules ?? (_rules = new List<Inputs.GetPolicyRuleArgs>());
            set => _rules = value;
        }

        public GetPolicyArgs()
        {
        }
        public static new GetPolicyArgs Empty => new GetPolicyArgs();
    }

    public sealed class GetPolicyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("rules")]
        private InputList<Inputs.GetPolicyRuleInputArgs>? _rules;
        public InputList<Inputs.GetPolicyRuleInputArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.GetPolicyRuleInputArgs>());
            set => _rules = value;
        }

        public GetPolicyInvokeArgs()
        {
        }
        public static new GetPolicyInvokeArgs Empty => new GetPolicyInvokeArgs();
    }


    [OutputType]
    public sealed class GetPolicyResult
    {
        public readonly string Description;
        public readonly bool Enabled;
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetPolicyRuleResult> Rules;
        public readonly ImmutableArray<string> SourcePostureChecks;

        [OutputConstructor]
        private GetPolicyResult(
            string description,

            bool enabled,

            string id,

            string name,

            ImmutableArray<Outputs.GetPolicyRuleResult> rules,

            ImmutableArray<string> sourcePostureChecks)
        {
            Description = description;
            Enabled = enabled;
            Id = id;
            Name = name;
            Rules = rules;
            SourcePostureChecks = sourcePostureChecks;
        }
    }
}
