// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetRoute
    {
        public static Task<GetRouteResult> InvokeAsync(GetRouteArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRouteResult>("netbird:index/getRoute:getRoute", args ?? new GetRouteArgs(), options.WithDefaults());

        public static Output<GetRouteResult> Invoke(GetRouteInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRouteResult>("netbird:index/getRoute:getRoute", args ?? new GetRouteInvokeArgs(), options.WithDefaults());

        public static Output<GetRouteResult> Invoke(GetRouteInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRouteResult>("netbird:index/getRoute:getRoute", args ?? new GetRouteInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRouteArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("networkId")]
        public string? NetworkId { get; set; }

        public GetRouteArgs()
        {
        }
        public static new GetRouteArgs Empty => new GetRouteArgs();
    }

    public sealed class GetRouteInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        public GetRouteInvokeArgs()
        {
        }
        public static new GetRouteInvokeArgs Empty => new GetRouteInvokeArgs();
    }


    [OutputType]
    public sealed class GetRouteResult
    {
        public readonly ImmutableArray<string> AccessControlGroups;
        public readonly string Description;
        public readonly ImmutableArray<string> Domains;
        public readonly bool Enabled;
        public readonly ImmutableArray<string> Groups;
        public readonly string Id;
        public readonly bool KeepRoute;
        public readonly bool Masquerade;
        public readonly int Metric;
        public readonly string Network;
        public readonly string NetworkId;
        public readonly string NetworkType;
        public readonly string Peer;
        public readonly ImmutableArray<string> PeerGroups;

        [OutputConstructor]
        private GetRouteResult(
            ImmutableArray<string> accessControlGroups,

            string description,

            ImmutableArray<string> domains,

            bool enabled,

            ImmutableArray<string> groups,

            string id,

            bool keepRoute,

            bool masquerade,

            int metric,

            string network,

            string networkId,

            string networkType,

            string peer,

            ImmutableArray<string> peerGroups)
        {
            AccessControlGroups = accessControlGroups;
            Description = description;
            Domains = domains;
            Enabled = enabled;
            Groups = groups;
            Id = id;
            KeepRoute = keepRoute;
            Masquerade = masquerade;
            Metric = metric;
            Network = network;
            NetworkId = networkId;
            NetworkType = networkType;
            Peer = peer;
            PeerGroups = peerGroups;
        }
    }
}
