// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetSetupKey
    {
        public static Task<GetSetupKeyResult> InvokeAsync(GetSetupKeyArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSetupKeyResult>("netbird:index/getSetupKey:getSetupKey", args ?? new GetSetupKeyArgs(), options.WithDefaults());

        public static Output<GetSetupKeyResult> Invoke(GetSetupKeyInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSetupKeyResult>("netbird:index/getSetupKey:getSetupKey", args ?? new GetSetupKeyInvokeArgs(), options.WithDefaults());

        public static Output<GetSetupKeyResult> Invoke(GetSetupKeyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSetupKeyResult>("netbird:index/getSetupKey:getSetupKey", args ?? new GetSetupKeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSetupKeyArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetSetupKeyArgs()
        {
        }
        public static new GetSetupKeyArgs Empty => new GetSetupKeyArgs();
    }

    public sealed class GetSetupKeyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetSetupKeyInvokeArgs()
        {
        }
        public static new GetSetupKeyInvokeArgs Empty => new GetSetupKeyInvokeArgs();
    }


    [OutputType]
    public sealed class GetSetupKeyResult
    {
        public readonly bool AllowExtraDnsLabels;
        public readonly ImmutableArray<string> AutoGroups;
        public readonly bool Ephemeral;
        public readonly string Expires;
        public readonly string Id;
        public readonly string LastUsed;
        public readonly string Name;
        public readonly bool Revoked;
        public readonly string State;
        public readonly string Type;
        public readonly string UpdatedAt;
        public readonly int UsageLimit;
        public readonly int UsedTimes;
        public readonly bool Valid;

        [OutputConstructor]
        private GetSetupKeyResult(
            bool allowExtraDnsLabels,

            ImmutableArray<string> autoGroups,

            bool ephemeral,

            string expires,

            string id,

            string lastUsed,

            string name,

            bool revoked,

            string state,

            string type,

            string updatedAt,

            int usageLimit,

            int usedTimes,

            bool valid)
        {
            AllowExtraDnsLabels = allowExtraDnsLabels;
            AutoGroups = autoGroups;
            Ephemeral = ephemeral;
            Expires = expires;
            Id = id;
            LastUsed = lastUsed;
            Name = name;
            Revoked = revoked;
            State = state;
            Type = type;
            UpdatedAt = updatedAt;
            UsageLimit = usageLimit;
            UsedTimes = usedTimes;
            Valid = valid;
        }
    }
}
