// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetToken
    {
        public static Task<GetTokenResult> InvokeAsync(GetTokenArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTokenResult>("netbird:index/getToken:getToken", args ?? new GetTokenArgs(), options.WithDefaults());

        public static Output<GetTokenResult> Invoke(GetTokenInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTokenResult>("netbird:index/getToken:getToken", args ?? new GetTokenInvokeArgs(), options.WithDefaults());

        public static Output<GetTokenResult> Invoke(GetTokenInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTokenResult>("netbird:index/getToken:getToken", args ?? new GetTokenInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTokenArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("userId", required: true)]
        public string UserId { get; set; } = null!;

        public GetTokenArgs()
        {
        }
        public static new GetTokenArgs Empty => new GetTokenArgs();
    }

    public sealed class GetTokenInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("userId", required: true)]
        public Input<string> UserId { get; set; } = null!;

        public GetTokenInvokeArgs()
        {
        }
        public static new GetTokenInvokeArgs Empty => new GetTokenInvokeArgs();
    }


    [OutputType]
    public sealed class GetTokenResult
    {
        public readonly string CreatedAt;
        public readonly string ExpirationDate;
        public readonly string Id;
        public readonly string LastUsed;
        public readonly string Name;
        public readonly string UserId;

        [OutputConstructor]
        private GetTokenResult(
            string createdAt,

            string expirationDate,

            string id,

            string lastUsed,

            string name,

            string userId)
        {
            CreatedAt = createdAt;
            ExpirationDate = expirationDate;
            Id = id;
            LastUsed = lastUsed;
            Name = name;
            UserId = userId;
        }
    }
}
