// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    public static class GetUser
    {
        public static Task<GetUserResult> InvokeAsync(GetUserArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUserResult>("netbird:index/getUser:getUser", args ?? new GetUserArgs(), options.WithDefaults());

        public static Output<GetUserResult> Invoke(GetUserInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserResult>("netbird:index/getUser:getUser", args ?? new GetUserInvokeArgs(), options.WithDefaults());

        public static Output<GetUserResult> Invoke(GetUserInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserResult>("netbird:index/getUser:getUser", args ?? new GetUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUserArgs : global::Pulumi.InvokeArgs
    {
        [Input("email")]
        public string? Email { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetUserArgs()
        {
        }
        public static new GetUserArgs Empty => new GetUserArgs();
    }

    public sealed class GetUserInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("email")]
        public Input<string>? Email { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetUserInvokeArgs()
        {
        }
        public static new GetUserInvokeArgs Empty => new GetUserInvokeArgs();
    }


    [OutputType]
    public sealed class GetUserResult
    {
        public readonly ImmutableArray<string> AutoGroups;
        public readonly string Email;
        public readonly string Id;
        public readonly bool IsBlocked;
        public readonly bool IsCurrent;
        public readonly bool IsServiceUser;
        public readonly string Issued;
        public readonly string LastLogin;
        public readonly string Name;
        public readonly string Role;
        public readonly string Status;

        [OutputConstructor]
        private GetUserResult(
            ImmutableArray<string> autoGroups,

            string email,

            string id,

            bool isBlocked,

            bool isCurrent,

            bool isServiceUser,

            string issued,

            string lastLogin,

            string name,

            string role,

            string status)
        {
            AutoGroups = autoGroups;
            Email = email;
            Id = id;
            IsBlocked = isBlocked;
            IsCurrent = isCurrent;
            IsServiceUser = isServiceUser;
            Issued = issued;
            LastLogin = lastLogin;
            Name = name;
            Role = role;
            Status = status;
        }
    }
}
