// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/group:Group")]
    public partial class Group : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Group issued by
        /// </summary>
        [Output("issued")]
        public Output<string> Issued { get; private set; } = null!;

        /// <summary>
        /// Group name identifier
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// List of peers ids
        /// </summary>
        [Output("peers")]
        public Output<ImmutableArray<string>> Peers { get; private set; } = null!;

        /// <summary>
        /// List of network resource ids
        /// </summary>
        [Output("resources")]
        public Output<ImmutableArray<string>> Resources { get; private set; } = null!;


        /// <summary>
        /// Create a Group resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Group(string name, GroupArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/group:Group", name, args ?? new GroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Group(string name, Input<string> id, GroupState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/group:Group", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Group resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Group Get(string name, Input<string> id, GroupState? state = null, CustomResourceOptions? options = null)
        {
            return new Group(name, id, state, options);
        }
    }

    public sealed class GroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group name identifier
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("peers")]
        private InputList<string>? _peers;

        /// <summary>
        /// List of peers ids
        /// </summary>
        public InputList<string> Peers
        {
            get => _peers ?? (_peers = new InputList<string>());
            set => _peers = value;
        }

        [Input("resources")]
        private InputList<string>? _resources;

        /// <summary>
        /// List of network resource ids
        /// </summary>
        public InputList<string> Resources
        {
            get => _resources ?? (_resources = new InputList<string>());
            set => _resources = value;
        }

        public GroupArgs()
        {
        }
        public static new GroupArgs Empty => new GroupArgs();
    }

    public sealed class GroupState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group issued by
        /// </summary>
        [Input("issued")]
        public Input<string>? Issued { get; set; }

        /// <summary>
        /// Group name identifier
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("peers")]
        private InputList<string>? _peers;

        /// <summary>
        /// List of peers ids
        /// </summary>
        public InputList<string> Peers
        {
            get => _peers ?? (_peers = new InputList<string>());
            set => _peers = value;
        }

        [Input("resources")]
        private InputList<string>? _resources;

        /// <summary>
        /// List of network resource ids
        /// </summary>
        public InputList<string> Resources
        {
            get => _resources ?? (_resources = new InputList<string>());
            set => _resources = value;
        }

        public GroupState()
        {
        }
        public static new GroupState Empty => new GroupState();
    }
}
