// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/nameserverGroup:NameserverGroup")]
    public partial class NameserverGroup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Description of the nameserver group
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Match domain list. It should be empty only if primary is true.
        /// </summary>
        [Output("domains")]
        public Output<ImmutableArray<string>> Domains { get; private set; } = null!;

        /// <summary>
        /// Nameserver group status
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Distribution group IDs that defines group of peers that will use this nameserver group
        /// </summary>
        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        /// <summary>
        /// Name of nameserver group
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Nameserver list
        /// </summary>
        [Output("nameservers")]
        public Output<ImmutableArray<Outputs.NameserverGroupNameserver>> Nameservers { get; private set; } = null!;

        /// <summary>
        /// Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        /// </summary>
        [Output("primary")]
        public Output<bool> Primary { get; private set; } = null!;

        /// <summary>
        /// Search domain status for match domains. It should be true only if domains list is not empty.
        /// </summary>
        [Output("searchDomainsEnabled")]
        public Output<bool> SearchDomainsEnabled { get; private set; } = null!;


        /// <summary>
        /// Create a NameserverGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NameserverGroup(string name, NameserverGroupArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/nameserverGroup:NameserverGroup", name, args ?? new NameserverGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NameserverGroup(string name, Input<string> id, NameserverGroupState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/nameserverGroup:NameserverGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NameserverGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NameserverGroup Get(string name, Input<string> id, NameserverGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new NameserverGroup(name, id, state, options);
        }
    }

    public sealed class NameserverGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the nameserver group
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domains")]
        private InputList<string>? _domains;

        /// <summary>
        /// Match domain list. It should be empty only if primary is true.
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// Nameserver group status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("groups", required: true)]
        private InputList<string>? _groups;

        /// <summary>
        /// Distribution group IDs that defines group of peers that will use this nameserver group
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// Name of nameserver group
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("nameservers", required: true)]
        private InputList<Inputs.NameserverGroupNameserverArgs>? _nameservers;

        /// <summary>
        /// Nameserver list
        /// </summary>
        public InputList<Inputs.NameserverGroupNameserverArgs> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<Inputs.NameserverGroupNameserverArgs>());
            set => _nameservers = value;
        }

        /// <summary>
        /// Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        /// </summary>
        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        /// <summary>
        /// Search domain status for match domains. It should be true only if domains list is not empty.
        /// </summary>
        [Input("searchDomainsEnabled")]
        public Input<bool>? SearchDomainsEnabled { get; set; }

        public NameserverGroupArgs()
        {
        }
        public static new NameserverGroupArgs Empty => new NameserverGroupArgs();
    }

    public sealed class NameserverGroupState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the nameserver group
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domains")]
        private InputList<string>? _domains;

        /// <summary>
        /// Match domain list. It should be empty only if primary is true.
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// Nameserver group status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;

        /// <summary>
        /// Distribution group IDs that defines group of peers that will use this nameserver group
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// Name of nameserver group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nameservers")]
        private InputList<Inputs.NameserverGroupNameserverGetArgs>? _nameservers;

        /// <summary>
        /// Nameserver list
        /// </summary>
        public InputList<Inputs.NameserverGroupNameserverGetArgs> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<Inputs.NameserverGroupNameserverGetArgs>());
            set => _nameservers = value;
        }

        /// <summary>
        /// Defines if a nameserver group is primary that resolves all domains. It should be true only if domains list is empty.
        /// </summary>
        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        /// <summary>
        /// Search domain status for match domains. It should be true only if domains list is not empty.
        /// </summary>
        [Input("searchDomainsEnabled")]
        public Input<bool>? SearchDomainsEnabled { get; set; }

        public NameserverGroupState()
        {
        }
        public static new NameserverGroupState Empty => new NameserverGroupState();
    }
}
