// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/networkRouter:NetworkRouter")]
    public partial class NetworkRouter : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Network router status
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Indicate if peer should masquerade traffic to this route's prefix
        /// </summary>
        [Output("masquerade")]
        public Output<bool> Masquerade { get; private set; } = null!;

        /// <summary>
        /// Route metric number. Lowest number has higher priority
        /// </summary>
        [Output("metric")]
        public Output<int> Metric { get; private set; } = null!;

        /// <summary>
        /// The unique identifier of a network
        /// </summary>
        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        /// <summary>
        /// Peer Identifier associated with route. This property can not be set together with peer_groups
        /// </summary>
        [Output("peer")]
        public Output<string?> Peer { get; private set; } = null!;

        /// <summary>
        /// Peers Group Identifier associated with route. This property can not be set together with peer
        /// </summary>
        [Output("peerGroups")]
        public Output<ImmutableArray<string>> PeerGroups { get; private set; } = null!;


        /// <summary>
        /// Create a NetworkRouter resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NetworkRouter(string name, NetworkRouterArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/networkRouter:NetworkRouter", name, args ?? new NetworkRouterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NetworkRouter(string name, Input<string> id, NetworkRouterState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/networkRouter:NetworkRouter", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NetworkRouter resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NetworkRouter Get(string name, Input<string> id, NetworkRouterState? state = null, CustomResourceOptions? options = null)
        {
            return new NetworkRouter(name, id, state, options);
        }
    }

    public sealed class NetworkRouterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Network router status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Indicate if peer should masquerade traffic to this route's prefix
        /// </summary>
        [Input("masquerade")]
        public Input<bool>? Masquerade { get; set; }

        /// <summary>
        /// Route metric number. Lowest number has higher priority
        /// </summary>
        [Input("metric")]
        public Input<int>? Metric { get; set; }

        /// <summary>
        /// The unique identifier of a network
        /// </summary>
        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        /// <summary>
        /// Peer Identifier associated with route. This property can not be set together with peer_groups
        /// </summary>
        [Input("peer")]
        public Input<string>? Peer { get; set; }

        [Input("peerGroups")]
        private InputList<string>? _peerGroups;

        /// <summary>
        /// Peers Group Identifier associated with route. This property can not be set together with peer
        /// </summary>
        public InputList<string> PeerGroups
        {
            get => _peerGroups ?? (_peerGroups = new InputList<string>());
            set => _peerGroups = value;
        }

        public NetworkRouterArgs()
        {
        }
        public static new NetworkRouterArgs Empty => new NetworkRouterArgs();
    }

    public sealed class NetworkRouterState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Network router status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Indicate if peer should masquerade traffic to this route's prefix
        /// </summary>
        [Input("masquerade")]
        public Input<bool>? Masquerade { get; set; }

        /// <summary>
        /// Route metric number. Lowest number has higher priority
        /// </summary>
        [Input("metric")]
        public Input<int>? Metric { get; set; }

        /// <summary>
        /// The unique identifier of a network
        /// </summary>
        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        /// <summary>
        /// Peer Identifier associated with route. This property can not be set together with peer_groups
        /// </summary>
        [Input("peer")]
        public Input<string>? Peer { get; set; }

        [Input("peerGroups")]
        private InputList<string>? _peerGroups;

        /// <summary>
        /// Peers Group Identifier associated with route. This property can not be set together with peer
        /// </summary>
        public InputList<string> PeerGroups
        {
            get => _peerGroups ?? (_peerGroups = new InputList<string>());
            set => _peerGroups = value;
        }

        public NetworkRouterState()
        {
        }
        public static new NetworkRouterState Empty => new NetworkRouterState();
    }
}
