// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/postureCheck:PostureCheck")]
    public partial class PostureCheck : global::Pulumi.CustomResource
    {
        /// <summary>
        /// PostureCheck description
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("geoLocationCheck")]
        public Output<Outputs.PostureCheckGeoLocationCheck?> GeoLocationCheck { get; private set; } = null!;

        /// <summary>
        /// PostureCheck Name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("netbirdVersionCheck")]
        public Output<Outputs.PostureCheckNetbirdVersionCheck?> NetbirdVersionCheck { get; private set; } = null!;

        [Output("osVersionCheck")]
        public Output<Outputs.PostureCheckOsVersionCheck?> OsVersionCheck { get; private set; } = null!;

        [Output("peerNetworkRangeCheck")]
        public Output<Outputs.PostureCheckPeerNetworkRangeCheck?> PeerNetworkRangeCheck { get; private set; } = null!;

        [Output("processChecks")]
        public Output<ImmutableArray<Outputs.PostureCheckProcessCheck>> ProcessChecks { get; private set; } = null!;


        /// <summary>
        /// Create a PostureCheck resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PostureCheck(string name, PostureCheckArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/postureCheck:PostureCheck", name, args ?? new PostureCheckArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PostureCheck(string name, Input<string> id, PostureCheckState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/postureCheck:PostureCheck", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PostureCheck resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PostureCheck Get(string name, Input<string> id, PostureCheckState? state = null, CustomResourceOptions? options = null)
        {
            return new PostureCheck(name, id, state, options);
        }
    }

    public sealed class PostureCheckArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// PostureCheck description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("geoLocationCheck")]
        public Input<Inputs.PostureCheckGeoLocationCheckArgs>? GeoLocationCheck { get; set; }

        /// <summary>
        /// PostureCheck Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("netbirdVersionCheck")]
        public Input<Inputs.PostureCheckNetbirdVersionCheckArgs>? NetbirdVersionCheck { get; set; }

        [Input("osVersionCheck")]
        public Input<Inputs.PostureCheckOsVersionCheckArgs>? OsVersionCheck { get; set; }

        [Input("peerNetworkRangeCheck")]
        public Input<Inputs.PostureCheckPeerNetworkRangeCheckArgs>? PeerNetworkRangeCheck { get; set; }

        [Input("processChecks")]
        private InputList<Inputs.PostureCheckProcessCheckArgs>? _processChecks;
        public InputList<Inputs.PostureCheckProcessCheckArgs> ProcessChecks
        {
            get => _processChecks ?? (_processChecks = new InputList<Inputs.PostureCheckProcessCheckArgs>());
            set => _processChecks = value;
        }

        public PostureCheckArgs()
        {
        }
        public static new PostureCheckArgs Empty => new PostureCheckArgs();
    }

    public sealed class PostureCheckState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// PostureCheck description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("geoLocationCheck")]
        public Input<Inputs.PostureCheckGeoLocationCheckGetArgs>? GeoLocationCheck { get; set; }

        /// <summary>
        /// PostureCheck Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("netbirdVersionCheck")]
        public Input<Inputs.PostureCheckNetbirdVersionCheckGetArgs>? NetbirdVersionCheck { get; set; }

        [Input("osVersionCheck")]
        public Input<Inputs.PostureCheckOsVersionCheckGetArgs>? OsVersionCheck { get; set; }

        [Input("peerNetworkRangeCheck")]
        public Input<Inputs.PostureCheckPeerNetworkRangeCheckGetArgs>? PeerNetworkRangeCheck { get; set; }

        [Input("processChecks")]
        private InputList<Inputs.PostureCheckProcessCheckGetArgs>? _processChecks;
        public InputList<Inputs.PostureCheckProcessCheckGetArgs> ProcessChecks
        {
            get => _processChecks ?? (_processChecks = new InputList<Inputs.PostureCheckProcessCheckGetArgs>());
            set => _processChecks = value;
        }

        public PostureCheckState()
        {
        }
        public static new PostureCheckState Empty => new PostureCheckState();
    }
}
