// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/route:Route")]
    public partial class Route : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Access control group identifier associated with route.
        /// </summary>
        [Output("accessControlGroups")]
        public Output<ImmutableArray<string>> AccessControlGroups { get; private set; } = null!;

        /// <summary>
        /// Route description
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
        /// </summary>
        [Output("domains")]
        public Output<ImmutableArray<string>> Domains { get; private set; } = null!;

        /// <summary>
        /// Route status
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Group IDs containing routing peers
        /// </summary>
        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        /// <summary>
        /// Indicate if the route should be kept after a domain doesn't resolve that IP anymore
        /// </summary>
        [Output("keepRoute")]
        public Output<bool> KeepRoute { get; private set; } = null!;

        /// <summary>
        /// Indicate if peer should masquerade traffic to this route's prefix
        /// </summary>
        [Output("masquerade")]
        public Output<bool> Masquerade { get; private set; } = null!;

        /// <summary>
        /// Route metric number. Lowest number has higher priority
        /// </summary>
        [Output("metric")]
        public Output<int> Metric { get; private set; } = null!;

        /// <summary>
        /// Network range in CIDR format, Conflicts with domains
        /// </summary>
        [Output("network")]
        public Output<string?> Network { get; private set; } = null!;

        /// <summary>
        /// Route network identifier, to group HA routes
        /// </summary>
        [Output("networkId")]
        public Output<string> NetworkId { get; private set; } = null!;

        /// <summary>
        /// Domain or IPv4
        /// </summary>
        [Output("networkType")]
        public Output<string> NetworkType { get; private set; } = null!;

        /// <summary>
        /// Peer Identifier associated with route. This property can not be set together with peer_groups
        /// </summary>
        [Output("peer")]
        public Output<string?> Peer { get; private set; } = null!;

        /// <summary>
        /// Peers Group Identifier associated with route. This property can not be set together with peer
        /// </summary>
        [Output("peerGroups")]
        public Output<ImmutableArray<string>> PeerGroups { get; private set; } = null!;


        /// <summary>
        /// Create a Route resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Route(string name, RouteArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/route:Route", name, args ?? new RouteArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Route(string name, Input<string> id, RouteState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/route:Route", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Route resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Route Get(string name, Input<string> id, RouteState? state = null, CustomResourceOptions? options = null)
        {
            return new Route(name, id, state, options);
        }
    }

    public sealed class RouteArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessControlGroups")]
        private InputList<string>? _accessControlGroups;

        /// <summary>
        /// Access control group identifier associated with route.
        /// </summary>
        public InputList<string> AccessControlGroups
        {
            get => _accessControlGroups ?? (_accessControlGroups = new InputList<string>());
            set => _accessControlGroups = value;
        }

        /// <summary>
        /// Route description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domains")]
        private InputList<string>? _domains;

        /// <summary>
        /// Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// Route status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("groups", required: true)]
        private InputList<string>? _groups;

        /// <summary>
        /// Group IDs containing routing peers
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// Indicate if the route should be kept after a domain doesn't resolve that IP anymore
        /// </summary>
        [Input("keepRoute")]
        public Input<bool>? KeepRoute { get; set; }

        /// <summary>
        /// Indicate if peer should masquerade traffic to this route's prefix
        /// </summary>
        [Input("masquerade")]
        public Input<bool>? Masquerade { get; set; }

        /// <summary>
        /// Route metric number. Lowest number has higher priority
        /// </summary>
        [Input("metric")]
        public Input<int>? Metric { get; set; }

        /// <summary>
        /// Network range in CIDR format, Conflicts with domains
        /// </summary>
        [Input("network")]
        public Input<string>? Network { get; set; }

        /// <summary>
        /// Route network identifier, to group HA routes
        /// </summary>
        [Input("networkId", required: true)]
        public Input<string> NetworkId { get; set; } = null!;

        /// <summary>
        /// Peer Identifier associated with route. This property can not be set together with peer_groups
        /// </summary>
        [Input("peer")]
        public Input<string>? Peer { get; set; }

        [Input("peerGroups")]
        private InputList<string>? _peerGroups;

        /// <summary>
        /// Peers Group Identifier associated with route. This property can not be set together with peer
        /// </summary>
        public InputList<string> PeerGroups
        {
            get => _peerGroups ?? (_peerGroups = new InputList<string>());
            set => _peerGroups = value;
        }

        public RouteArgs()
        {
        }
        public static new RouteArgs Empty => new RouteArgs();
    }

    public sealed class RouteState : global::Pulumi.ResourceArgs
    {
        [Input("accessControlGroups")]
        private InputList<string>? _accessControlGroups;

        /// <summary>
        /// Access control group identifier associated with route.
        /// </summary>
        public InputList<string> AccessControlGroups
        {
            get => _accessControlGroups ?? (_accessControlGroups = new InputList<string>());
            set => _accessControlGroups = value;
        }

        /// <summary>
        /// Route description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("domains")]
        private InputList<string>? _domains;

        /// <summary>
        /// Domain list to be dynamically resolved. Max of 32 domains can be added per route configuration. Conflicts with network
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// Route status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;

        /// <summary>
        /// Group IDs containing routing peers
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// Indicate if the route should be kept after a domain doesn't resolve that IP anymore
        /// </summary>
        [Input("keepRoute")]
        public Input<bool>? KeepRoute { get; set; }

        /// <summary>
        /// Indicate if peer should masquerade traffic to this route's prefix
        /// </summary>
        [Input("masquerade")]
        public Input<bool>? Masquerade { get; set; }

        /// <summary>
        /// Route metric number. Lowest number has higher priority
        /// </summary>
        [Input("metric")]
        public Input<int>? Metric { get; set; }

        /// <summary>
        /// Network range in CIDR format, Conflicts with domains
        /// </summary>
        [Input("network")]
        public Input<string>? Network { get; set; }

        /// <summary>
        /// Route network identifier, to group HA routes
        /// </summary>
        [Input("networkId")]
        public Input<string>? NetworkId { get; set; }

        /// <summary>
        /// Domain or IPv4
        /// </summary>
        [Input("networkType")]
        public Input<string>? NetworkType { get; set; }

        /// <summary>
        /// Peer Identifier associated with route. This property can not be set together with peer_groups
        /// </summary>
        [Input("peer")]
        public Input<string>? Peer { get; set; }

        [Input("peerGroups")]
        private InputList<string>? _peerGroups;

        /// <summary>
        /// Peers Group Identifier associated with route. This property can not be set together with peer
        /// </summary>
        public InputList<string> PeerGroups
        {
            get => _peerGroups ?? (_peerGroups = new InputList<string>());
            set => _peerGroups = value;
        }

        public RouteState()
        {
        }
        public static new RouteState Empty => new RouteState();
    }
}
