// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/setupKey:SetupKey")]
    public partial class SetupKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Allow extra DNS labels to be added to the peer
        /// </summary>
        [Output("allowExtraDnsLabels")]
        public Output<bool> AllowExtraDnsLabels { get; private set; } = null!;

        /// <summary>
        /// List of groups to automatically assign to peers created through this setup key
        /// </summary>
        [Output("autoGroups")]
        public Output<ImmutableArray<string>> AutoGroups { get; private set; } = null!;

        /// <summary>
        /// Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        /// </summary>
        [Output("ephemeral")]
        public Output<bool> Ephemeral { get; private set; } = null!;

        /// <summary>
        /// SetupKey Expiration Date
        /// </summary>
        [Output("expires")]
        public Output<string> Expires { get; private set; } = null!;

        /// <summary>
        /// Expiry time in seconds (0 is unlimited)
        /// </summary>
        [Output("expirySeconds")]
        public Output<int> ExpirySeconds { get; private set; } = null!;

        /// <summary>
        /// Plaintext setup key
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Last usage time
        /// </summary>
        [Output("lastUsed")]
        public Output<string> LastUsed { get; private set; } = null!;

        /// <summary>
        /// SetupKey Name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Set to true to revoke setup key
        /// </summary>
        [Output("revoked")]
        public Output<bool> Revoked { get; private set; } = null!;

        /// <summary>
        /// Setup key state (valid or expired)
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// Setup Key type (one-off or reusable)
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Maximum number of times SetupKey can be used (0 for unlimited)
        /// </summary>
        [Output("usageLimit")]
        public Output<int> UsageLimit { get; private set; } = null!;

        /// <summary>
        /// Number of times Setup Key was used
        /// </summary>
        [Output("usedTimes")]
        public Output<int> UsedTimes { get; private set; } = null!;

        /// <summary>
        /// True if setup key can be used to create more Peers
        /// </summary>
        [Output("valid")]
        public Output<bool> Valid { get; private set; } = null!;


        /// <summary>
        /// Create a SetupKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SetupKey(string name, SetupKeyArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/setupKey:SetupKey", name, args ?? new SetupKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SetupKey(string name, Input<string> id, SetupKeyState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/setupKey:SetupKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
                AdditionalSecretOutputs =
                {
                    "key",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SetupKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SetupKey Get(string name, Input<string> id, SetupKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new SetupKey(name, id, state, options);
        }
    }

    public sealed class SetupKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allow extra DNS labels to be added to the peer
        /// </summary>
        [Input("allowExtraDnsLabels")]
        public Input<bool>? AllowExtraDnsLabels { get; set; }

        [Input("autoGroups")]
        private InputList<string>? _autoGroups;

        /// <summary>
        /// List of groups to automatically assign to peers created through this setup key
        /// </summary>
        public InputList<string> AutoGroups
        {
            get => _autoGroups ?? (_autoGroups = new InputList<string>());
            set => _autoGroups = value;
        }

        /// <summary>
        /// Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        /// </summary>
        [Input("ephemeral")]
        public Input<bool>? Ephemeral { get; set; }

        /// <summary>
        /// Expiry time in seconds (0 is unlimited)
        /// </summary>
        [Input("expirySeconds")]
        public Input<int>? ExpirySeconds { get; set; }

        /// <summary>
        /// SetupKey Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Set to true to revoke setup key
        /// </summary>
        [Input("revoked")]
        public Input<bool>? Revoked { get; set; }

        /// <summary>
        /// Setup Key type (one-off or reusable)
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Maximum number of times SetupKey can be used (0 for unlimited)
        /// </summary>
        [Input("usageLimit")]
        public Input<int>? UsageLimit { get; set; }

        public SetupKeyArgs()
        {
        }
        public static new SetupKeyArgs Empty => new SetupKeyArgs();
    }

    public sealed class SetupKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allow extra DNS labels to be added to the peer
        /// </summary>
        [Input("allowExtraDnsLabels")]
        public Input<bool>? AllowExtraDnsLabels { get; set; }

        [Input("autoGroups")]
        private InputList<string>? _autoGroups;

        /// <summary>
        /// List of groups to automatically assign to peers created through this setup key
        /// </summary>
        public InputList<string> AutoGroups
        {
            get => _autoGroups ?? (_autoGroups = new InputList<string>());
            set => _autoGroups = value;
        }

        /// <summary>
        /// Indicate that the peer will be ephemeral or not, ephemeral peers are deleted after 10 minutes of inactivity
        /// </summary>
        [Input("ephemeral")]
        public Input<bool>? Ephemeral { get; set; }

        /// <summary>
        /// SetupKey Expiration Date
        /// </summary>
        [Input("expires")]
        public Input<string>? Expires { get; set; }

        /// <summary>
        /// Expiry time in seconds (0 is unlimited)
        /// </summary>
        [Input("expirySeconds")]
        public Input<int>? ExpirySeconds { get; set; }

        [Input("key")]
        private Input<string>? _key;

        /// <summary>
        /// Plaintext setup key
        /// </summary>
        public Input<string>? Key
        {
            get => _key;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _key = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Last usage time
        /// </summary>
        [Input("lastUsed")]
        public Input<string>? LastUsed { get; set; }

        /// <summary>
        /// SetupKey Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Set to true to revoke setup key
        /// </summary>
        [Input("revoked")]
        public Input<bool>? Revoked { get; set; }

        /// <summary>
        /// Setup key state (valid or expired)
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// Setup Key type (one-off or reusable)
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        /// <summary>
        /// Maximum number of times SetupKey can be used (0 for unlimited)
        /// </summary>
        [Input("usageLimit")]
        public Input<int>? UsageLimit { get; set; }

        /// <summary>
        /// Number of times Setup Key was used
        /// </summary>
        [Input("usedTimes")]
        public Input<int>? UsedTimes { get; set; }

        /// <summary>
        /// True if setup key can be used to create more Peers
        /// </summary>
        [Input("valid")]
        public Input<bool>? Valid { get; set; }

        public SetupKeyState()
        {
        }
        public static new SetupKeyState Empty => new SetupKeyState();
    }
}
