// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird
{
    [NetbirdResourceType("netbird:index/user:User")]
    public partial class User : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Group IDs to auto-assign to peers registered by this user
        /// </summary>
        [Output("autoGroups")]
        public Output<ImmutableArray<string>> AutoGroups { get; private set; } = null!;

        /// <summary>
        /// User Email
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// If set to true then user is blocked and can't use the system
        /// </summary>
        [Output("isBlocked")]
        public Output<bool> IsBlocked { get; private set; } = null!;

        /// <summary>
        /// Set to true if the caller user is the same as the resource user
        /// </summary>
        [Output("isCurrent")]
        public Output<bool> IsCurrent { get; private set; } = null!;

        /// <summary>
        /// If set to true, creates a Service Account User
        /// </summary>
        [Output("isServiceUser")]
        public Output<bool> IsServiceUser { get; private set; } = null!;

        /// <summary>
        /// User issue method
        /// </summary>
        [Output("issued")]
        public Output<string> Issued { get; private set; } = null!;

        /// <summary>
        /// User Last Login timedate
        /// </summary>
        [Output("lastLogin")]
        public Output<string> LastLogin { get; private set; } = null!;

        /// <summary>
        /// User Name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// User's NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// User status (active or invited)
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a User resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public User(string name, UserArgs args, CustomResourceOptions? options = null)
            : base("netbird:index/user:User", name, args ?? new UserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private User(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
            : base("netbird:index/user:User", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/KitStream/netbird-pulumi-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing User resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static User Get(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
        {
            return new User(name, id, state, options);
        }
    }

    public sealed class UserArgs : global::Pulumi.ResourceArgs
    {
        [Input("autoGroups")]
        private InputList<string>? _autoGroups;

        /// <summary>
        /// Group IDs to auto-assign to peers registered by this user
        /// </summary>
        public InputList<string> AutoGroups
        {
            get => _autoGroups ?? (_autoGroups = new InputList<string>());
            set => _autoGroups = value;
        }

        /// <summary>
        /// User Email
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// If set to true then user is blocked and can't use the system
        /// </summary>
        [Input("isBlocked")]
        public Input<bool>? IsBlocked { get; set; }

        /// <summary>
        /// If set to true, creates a Service Account User
        /// </summary>
        [Input("isServiceUser", required: true)]
        public Input<bool> IsServiceUser { get; set; } = null!;

        /// <summary>
        /// User Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// User's NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        public UserArgs()
        {
        }
        public static new UserArgs Empty => new UserArgs();
    }

    public sealed class UserState : global::Pulumi.ResourceArgs
    {
        [Input("autoGroups")]
        private InputList<string>? _autoGroups;

        /// <summary>
        /// Group IDs to auto-assign to peers registered by this user
        /// </summary>
        public InputList<string> AutoGroups
        {
            get => _autoGroups ?? (_autoGroups = new InputList<string>());
            set => _autoGroups = value;
        }

        /// <summary>
        /// User Email
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// If set to true then user is blocked and can't use the system
        /// </summary>
        [Input("isBlocked")]
        public Input<bool>? IsBlocked { get; set; }

        /// <summary>
        /// Set to true if the caller user is the same as the resource user
        /// </summary>
        [Input("isCurrent")]
        public Input<bool>? IsCurrent { get; set; }

        /// <summary>
        /// If set to true, creates a Service Account User
        /// </summary>
        [Input("isServiceUser")]
        public Input<bool>? IsServiceUser { get; set; }

        /// <summary>
        /// User issue method
        /// </summary>
        [Input("issued")]
        public Input<string>? Issued { get; set; }

        /// <summary>
        /// User Last Login timedate
        /// </summary>
        [Input("lastLogin")]
        public Input<string>? LastLogin { get; set; }

        /// <summary>
        /// User Name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// User's NetBird account role (owner|admin|user|billing_admin|auditor|network_admin).
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// User status (active or invited)
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public UserState()
        {
        }
        public static new UserState Empty => new UserState();
    }
}
