// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class GetPolicyRuleArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Policy Rule Action (accept|drop)
        /// </summary>
        [Input("action", required: true)]
        public string Action { get; set; } = null!;

        /// <summary>
        /// Policy Rule Bidirectional
        /// </summary>
        [Input("bidirectional", required: true)]
        public bool Bidirectional { get; set; }

        /// <summary>
        /// Policy description
        /// </summary>
        [Input("description", required: true)]
        public string Description { get; set; } = null!;

        /// <summary>
        /// Policy Rule Destination Resource (mutually exclusive with destinations)
        /// </summary>
        [Input("destinationResource", required: true)]
        public Inputs.GetPolicyRuleDestinationResourceArgs DestinationResource { get; set; } = null!;

        [Input("destinations", required: true)]
        private List<string>? _destinations;

        /// <summary>
        /// Policy Rule Destination Groups (mutually exclusive with destination_resource)
        /// </summary>
        public List<string> Destinations
        {
            get => _destinations ?? (_destinations = new List<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// Policy Rule Enabled
        /// </summary>
        [Input("enabled", required: true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Policy ID
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// Policy Name
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("portRanges", required: true)]
        private List<Inputs.GetPolicyRulePortRangeArgs>? _portRanges;

        /// <summary>
        /// Policy Rule Port Ranges (mutually exclusive with ports)
        /// </summary>
        public List<Inputs.GetPolicyRulePortRangeArgs> PortRanges
        {
            get => _portRanges ?? (_portRanges = new List<Inputs.GetPolicyRulePortRangeArgs>());
            set => _portRanges = value;
        }

        [Input("ports", required: true)]
        private List<string>? _ports;

        /// <summary>
        /// Policy Rule Ports (mutually exclusive with port_ranges)
        /// </summary>
        public List<string> Ports
        {
            get => _ports ?? (_ports = new List<string>());
            set => _ports = value;
        }

        /// <summary>
        /// Policy Rule Protocol (tcp|udp|icmp|all)
        /// </summary>
        [Input("protocol", required: true)]
        public string Protocol { get; set; } = null!;

        /// <summary>
        /// Policy Rule Source Resource (mutually exclusive with sources)
        /// </summary>
        [Input("sourceResource", required: true)]
        public Inputs.GetPolicyRuleSourceResourceArgs SourceResource { get; set; } = null!;

        [Input("sources", required: true)]
        private List<string>? _sources;

        /// <summary>
        /// Policy Rule Source Groups (mutually exclusive with source_resource)
        /// </summary>
        public List<string> Sources
        {
            get => _sources ?? (_sources = new List<string>());
            set => _sources = value;
        }

        public GetPolicyRuleArgs()
        {
        }
        public static new GetPolicyRuleArgs Empty => new GetPolicyRuleArgs();
    }
}
