// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class GetPolicyRuleInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Policy Rule Action (accept|drop)
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        /// <summary>
        /// Policy Rule Bidirectional
        /// </summary>
        [Input("bidirectional", required: true)]
        public Input<bool> Bidirectional { get; set; } = null!;

        /// <summary>
        /// Policy description
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Policy Rule Destination Resource (mutually exclusive with destinations)
        /// </summary>
        [Input("destinationResource", required: true)]
        public Input<Inputs.GetPolicyRuleDestinationResourceInputArgs> DestinationResource { get; set; } = null!;

        [Input("destinations", required: true)]
        private InputList<string>? _destinations;

        /// <summary>
        /// Policy Rule Destination Groups (mutually exclusive with destination_resource)
        /// </summary>
        public InputList<string> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// Policy Rule Enabled
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Policy ID
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Policy Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("portRanges", required: true)]
        private InputList<Inputs.GetPolicyRulePortRangeInputArgs>? _portRanges;

        /// <summary>
        /// Policy Rule Port Ranges (mutually exclusive with ports)
        /// </summary>
        public InputList<Inputs.GetPolicyRulePortRangeInputArgs> PortRanges
        {
            get => _portRanges ?? (_portRanges = new InputList<Inputs.GetPolicyRulePortRangeInputArgs>());
            set => _portRanges = value;
        }

        [Input("ports", required: true)]
        private InputList<string>? _ports;

        /// <summary>
        /// Policy Rule Ports (mutually exclusive with port_ranges)
        /// </summary>
        public InputList<string> Ports
        {
            get => _ports ?? (_ports = new InputList<string>());
            set => _ports = value;
        }

        /// <summary>
        /// Policy Rule Protocol (tcp|udp|icmp|all)
        /// </summary>
        [Input("protocol", required: true)]
        public Input<string> Protocol { get; set; } = null!;

        /// <summary>
        /// Policy Rule Source Resource (mutually exclusive with sources)
        /// </summary>
        [Input("sourceResource", required: true)]
        public Input<Inputs.GetPolicyRuleSourceResourceInputArgs> SourceResource { get; set; } = null!;

        [Input("sources", required: true)]
        private InputList<string>? _sources;

        /// <summary>
        /// Policy Rule Source Groups (mutually exclusive with source_resource)
        /// </summary>
        public InputList<string> Sources
        {
            get => _sources ?? (_sources = new InputList<string>());
            set => _sources = value;
        }

        public GetPolicyRuleInputArgs()
        {
        }
        public static new GetPolicyRuleInputArgs Empty => new GetPolicyRuleInputArgs();
    }
}
