// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class GetPolicyRuleSourceResourceArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        public GetPolicyRuleSourceResourceArgs()
        {
        }
        public static new GetPolicyRuleSourceResourceArgs Empty => new GetPolicyRuleSourceResourceArgs();
    }
}
