// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class NameserverGroupNameserverGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Nameserver IP
        /// </summary>
        [Input("ip", required: true)]
        public Input<string> Ip { get; set; } = null!;

        /// <summary>
        /// Nameserver Type
        /// </summary>
        [Input("nsType")]
        public Input<string>? NsType { get; set; }

        /// <summary>
        /// Nameserver Port
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        public NameserverGroupNameserverGetArgs()
        {
        }
        public static new NameserverGroupNameserverGetArgs Empty => new NameserverGroupNameserverGetArgs();
    }
}
