// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PolicyRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Policy Rule Action (accept|drop)
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        /// <summary>
        /// Policy Rule Bidirectional
        /// </summary>
        [Input("bidirectional")]
        public Input<bool>? Bidirectional { get; set; }

        /// <summary>
        /// Policy description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Policy Rule Destination Resource (mutually exclusive with destinations)
        /// </summary>
        [Input("destinationResource")]
        public Input<Inputs.PolicyRuleDestinationResourceArgs>? DestinationResource { get; set; }

        [Input("destinations")]
        private InputList<string>? _destinations;

        /// <summary>
        /// Policy Rule Destination Groups (mutually exclusive with destination_resource)
        /// </summary>
        public InputList<string> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// Policy Rule Enabled
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Policy ID
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Policy Name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("portRanges")]
        private InputList<Inputs.PolicyRulePortRangeArgs>? _portRanges;

        /// <summary>
        /// Policy Rule Port Ranges (mutually exclusive with ports)
        /// </summary>
        public InputList<Inputs.PolicyRulePortRangeArgs> PortRanges
        {
            get => _portRanges ?? (_portRanges = new InputList<Inputs.PolicyRulePortRangeArgs>());
            set => _portRanges = value;
        }

        [Input("ports")]
        private InputList<string>? _ports;

        /// <summary>
        /// Policy Rule Ports (mutually exclusive with port_ranges)
        /// </summary>
        public InputList<string> Ports
        {
            get => _ports ?? (_ports = new InputList<string>());
            set => _ports = value;
        }

        /// <summary>
        /// Policy Rule Protocol (tcp|udp|icmp|all)
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        /// <summary>
        /// Policy Rule Source Resource (mutually exclusive with sources)
        /// </summary>
        [Input("sourceResource")]
        public Input<Inputs.PolicyRuleSourceResourceArgs>? SourceResource { get; set; }

        [Input("sources")]
        private InputList<string>? _sources;

        /// <summary>
        /// Policy Rule Source Groups (mutually exclusive with source_resource)
        /// </summary>
        public InputList<string> Sources
        {
            get => _sources ?? (_sources = new InputList<string>());
            set => _sources = value;
        }

        public PolicyRuleArgs()
        {
        }
        public static new PolicyRuleArgs Empty => new PolicyRuleArgs();
    }
}
