// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PostureCheckGeoLocationCheckGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("locations")]
        private InputList<Inputs.PostureCheckGeoLocationCheckLocationGetArgs>? _locations;
        public InputList<Inputs.PostureCheckGeoLocationCheckLocationGetArgs> Locations
        {
            get => _locations ?? (_locations = new InputList<Inputs.PostureCheckGeoLocationCheckLocationGetArgs>());
            set => _locations = value;
        }

        public PostureCheckGeoLocationCheckGetArgs()
        {
        }
        public static new PostureCheckGeoLocationCheckGetArgs Empty => new PostureCheckGeoLocationCheckGetArgs();
    }
}
