// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PostureCheckGeoLocationCheckLocationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("cityName")]
        public Input<string>? CityName { get; set; }

        [Input("countryCode", required: true)]
        public Input<string> CountryCode { get; set; } = null!;

        public PostureCheckGeoLocationCheckLocationGetArgs()
        {
        }
        public static new PostureCheckGeoLocationCheckLocationGetArgs Empty => new PostureCheckGeoLocationCheckLocationGetArgs();
    }
}
