// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PostureCheckOsVersionCheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("androidMinVersion")]
        public Input<string>? AndroidMinVersion { get; set; }

        [Input("darwinMinVersion")]
        public Input<string>? DarwinMinVersion { get; set; }

        [Input("iosMinVersion")]
        public Input<string>? IosMinVersion { get; set; }

        [Input("linuxMinKernelVersion")]
        public Input<string>? LinuxMinKernelVersion { get; set; }

        [Input("windowsMinKernelVersion")]
        public Input<string>? WindowsMinKernelVersion { get; set; }

        public PostureCheckOsVersionCheckArgs()
        {
        }
        public static new PostureCheckOsVersionCheckArgs Empty => new PostureCheckOsVersionCheckArgs();
    }
}
