// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PostureCheckProcessCheckGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("linuxPath")]
        public Input<string>? LinuxPath { get; set; }

        [Input("macPath")]
        public Input<string>? MacPath { get; set; }

        [Input("windowsPath")]
        public Input<string>? WindowsPath { get; set; }

        public PostureCheckProcessCheckGetArgs()
        {
        }
        public static new PostureCheckProcessCheckGetArgs Empty => new PostureCheckProcessCheckGetArgs();
    }
}
