// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PostureCheckPeerNetworkRangeCheckGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("ranges")]
        private InputList<string>? _ranges;
        public InputList<string> Ranges
        {
            get => _ranges ?? (_ranges = new InputList<string>());
            set => _ranges = value;
        }

        public PostureCheckPeerNetworkRangeCheckGetArgs()
        {
        }
        public static new PostureCheckPeerNetworkRangeCheckGetArgs Empty => new PostureCheckPeerNetworkRangeCheckGetArgs();
    }
}
