// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KitStream.Pulumi.Netbird.Inputs
{

    public sealed class PostureCheckNetbirdVersionCheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("minVersion")]
        public Input<string>? MinVersion { get; set; }

        public PostureCheckNetbirdVersionCheckArgs()
        {
        }
        public static new PostureCheckNetbirdVersionCheckArgs Empty => new PostureCheckNetbirdVersionCheckArgs();
    }
}
