// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AccountSettingsArgs, AccountSettingsState } from "./accountSettings";
export type AccountSettings = import("./accountSettings").AccountSettings;
export const AccountSettings: typeof import("./accountSettings").AccountSettings = null as any;
utilities.lazyLoad(exports, ["AccountSettings"], () => require("./accountSettings"));

export { DnsSettingsArgs, DnsSettingsState } from "./dnsSettings";
export type DnsSettings = import("./dnsSettings").DnsSettings;
export const DnsSettings: typeof import("./dnsSettings").DnsSettings = null as any;
utilities.lazyLoad(exports, ["DnsSettings"], () => require("./dnsSettings"));

export { GetAccountSettingsResult } from "./getAccountSettings";
export const getAccountSettings: typeof import("./getAccountSettings").getAccountSettings = null as any;
export const getAccountSettingsOutput: typeof import("./getAccountSettings").getAccountSettingsOutput = null as any;
utilities.lazyLoad(exports, ["getAccountSettings","getAccountSettingsOutput"], () => require("./getAccountSettings"));

export { GetDnsSettingsResult } from "./getDnsSettings";
export const getDnsSettings: typeof import("./getDnsSettings").getDnsSettings = null as any;
export const getDnsSettingsOutput: typeof import("./getDnsSettings").getDnsSettingsOutput = null as any;
utilities.lazyLoad(exports, ["getDnsSettings","getDnsSettingsOutput"], () => require("./getDnsSettings"));

export { GetGroupArgs, GetGroupResult, GetGroupOutputArgs } from "./getGroup";
export const getGroup: typeof import("./getGroup").getGroup = null as any;
export const getGroupOutput: typeof import("./getGroup").getGroupOutput = null as any;
utilities.lazyLoad(exports, ["getGroup","getGroupOutput"], () => require("./getGroup"));

export { GetNameserverGroupArgs, GetNameserverGroupResult, GetNameserverGroupOutputArgs } from "./getNameserverGroup";
export const getNameserverGroup: typeof import("./getNameserverGroup").getNameserverGroup = null as any;
export const getNameserverGroupOutput: typeof import("./getNameserverGroup").getNameserverGroupOutput = null as any;
utilities.lazyLoad(exports, ["getNameserverGroup","getNameserverGroupOutput"], () => require("./getNameserverGroup"));

export { GetNetworkArgs, GetNetworkResult, GetNetworkOutputArgs } from "./getNetwork";
export const getNetwork: typeof import("./getNetwork").getNetwork = null as any;
export const getNetworkOutput: typeof import("./getNetwork").getNetworkOutput = null as any;
utilities.lazyLoad(exports, ["getNetwork","getNetworkOutput"], () => require("./getNetwork"));

export { GetNetworkResourceArgs, GetNetworkResourceResult, GetNetworkResourceOutputArgs } from "./getNetworkResource";
export const getNetworkResource: typeof import("./getNetworkResource").getNetworkResource = null as any;
export const getNetworkResourceOutput: typeof import("./getNetworkResource").getNetworkResourceOutput = null as any;
utilities.lazyLoad(exports, ["getNetworkResource","getNetworkResourceOutput"], () => require("./getNetworkResource"));

export { GetNetworkRouterArgs, GetNetworkRouterResult, GetNetworkRouterOutputArgs } from "./getNetworkRouter";
export const getNetworkRouter: typeof import("./getNetworkRouter").getNetworkRouter = null as any;
export const getNetworkRouterOutput: typeof import("./getNetworkRouter").getNetworkRouterOutput = null as any;
utilities.lazyLoad(exports, ["getNetworkRouter","getNetworkRouterOutput"], () => require("./getNetworkRouter"));

export { GetPeerArgs, GetPeerResult, GetPeerOutputArgs } from "./getPeer";
export const getPeer: typeof import("./getPeer").getPeer = null as any;
export const getPeerOutput: typeof import("./getPeer").getPeerOutput = null as any;
utilities.lazyLoad(exports, ["getPeer","getPeerOutput"], () => require("./getPeer"));

export { GetPeersArgs, GetPeersResult, GetPeersOutputArgs } from "./getPeers";
export const getPeers: typeof import("./getPeers").getPeers = null as any;
export const getPeersOutput: typeof import("./getPeers").getPeersOutput = null as any;
utilities.lazyLoad(exports, ["getPeers","getPeersOutput"], () => require("./getPeers"));

export { GetPolicyArgs, GetPolicyResult, GetPolicyOutputArgs } from "./getPolicy";
export const getPolicy: typeof import("./getPolicy").getPolicy = null as any;
export const getPolicyOutput: typeof import("./getPolicy").getPolicyOutput = null as any;
utilities.lazyLoad(exports, ["getPolicy","getPolicyOutput"], () => require("./getPolicy"));

export { GetPostureCheckArgs, GetPostureCheckResult, GetPostureCheckOutputArgs } from "./getPostureCheck";
export const getPostureCheck: typeof import("./getPostureCheck").getPostureCheck = null as any;
export const getPostureCheckOutput: typeof import("./getPostureCheck").getPostureCheckOutput = null as any;
utilities.lazyLoad(exports, ["getPostureCheck","getPostureCheckOutput"], () => require("./getPostureCheck"));

export { GetRouteArgs, GetRouteResult, GetRouteOutputArgs } from "./getRoute";
export const getRoute: typeof import("./getRoute").getRoute = null as any;
export const getRouteOutput: typeof import("./getRoute").getRouteOutput = null as any;
utilities.lazyLoad(exports, ["getRoute","getRouteOutput"], () => require("./getRoute"));

export { GetSetupKeyArgs, GetSetupKeyResult, GetSetupKeyOutputArgs } from "./getSetupKey";
export const getSetupKey: typeof import("./getSetupKey").getSetupKey = null as any;
export const getSetupKeyOutput: typeof import("./getSetupKey").getSetupKeyOutput = null as any;
utilities.lazyLoad(exports, ["getSetupKey","getSetupKeyOutput"], () => require("./getSetupKey"));

export { GetTokenArgs, GetTokenResult, GetTokenOutputArgs } from "./getToken";
export const getToken: typeof import("./getToken").getToken = null as any;
export const getTokenOutput: typeof import("./getToken").getTokenOutput = null as any;
utilities.lazyLoad(exports, ["getToken","getTokenOutput"], () => require("./getToken"));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from "./getUser";
export const getUser: typeof import("./getUser").getUser = null as any;
export const getUserOutput: typeof import("./getUser").getUserOutput = null as any;
utilities.lazyLoad(exports, ["getUser","getUserOutput"], () => require("./getUser"));

export { GroupArgs, GroupState } from "./group";
export type Group = import("./group").Group;
export const Group: typeof import("./group").Group = null as any;
utilities.lazyLoad(exports, ["Group"], () => require("./group"));

export { NameserverGroupArgs, NameserverGroupState } from "./nameserverGroup";
export type NameserverGroup = import("./nameserverGroup").NameserverGroup;
export const NameserverGroup: typeof import("./nameserverGroup").NameserverGroup = null as any;
utilities.lazyLoad(exports, ["NameserverGroup"], () => require("./nameserverGroup"));

export { NetworkArgs, NetworkState } from "./network";
export type Network = import("./network").Network;
export const Network: typeof import("./network").Network = null as any;
utilities.lazyLoad(exports, ["Network"], () => require("./network"));

export { NetworkResourceArgs, NetworkResourceState } from "./networkResource";
export type NetworkResource = import("./networkResource").NetworkResource;
export const NetworkResource: typeof import("./networkResource").NetworkResource = null as any;
utilities.lazyLoad(exports, ["NetworkResource"], () => require("./networkResource"));

export { NetworkRouterArgs, NetworkRouterState } from "./networkRouter";
export type NetworkRouter = import("./networkRouter").NetworkRouter;
export const NetworkRouter: typeof import("./networkRouter").NetworkRouter = null as any;
utilities.lazyLoad(exports, ["NetworkRouter"], () => require("./networkRouter"));

export { PeerArgs, PeerState } from "./peer";
export type Peer = import("./peer").Peer;
export const Peer: typeof import("./peer").Peer = null as any;
utilities.lazyLoad(exports, ["Peer"], () => require("./peer"));

export { PersonalAccessTokenArgs, PersonalAccessTokenState } from "./personalAccessToken";
export type PersonalAccessToken = import("./personalAccessToken").PersonalAccessToken;
export const PersonalAccessToken: typeof import("./personalAccessToken").PersonalAccessToken = null as any;
utilities.lazyLoad(exports, ["PersonalAccessToken"], () => require("./personalAccessToken"));

export { PolicyArgs, PolicyState } from "./policy";
export type Policy = import("./policy").Policy;
export const Policy: typeof import("./policy").Policy = null as any;
utilities.lazyLoad(exports, ["Policy"], () => require("./policy"));

export { PostureCheckArgs, PostureCheckState } from "./postureCheck";
export type PostureCheck = import("./postureCheck").PostureCheck;
export const PostureCheck: typeof import("./postureCheck").PostureCheck = null as any;
utilities.lazyLoad(exports, ["PostureCheck"], () => require("./postureCheck"));

export * from "./provider";
import { Provider } from "./provider";

export { RouteArgs, RouteState } from "./route";
export type Route = import("./route").Route;
export const Route: typeof import("./route").Route = null as any;
utilities.lazyLoad(exports, ["Route"], () => require("./route"));

export { SetupKeyArgs, SetupKeyState } from "./setupKey";
export type SetupKey = import("./setupKey").SetupKey;
export const SetupKey: typeof import("./setupKey").SetupKey = null as any;
utilities.lazyLoad(exports, ["SetupKey"], () => require("./setupKey"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "netbird:index/accountSettings:AccountSettings":
                return new AccountSettings(name, <any>undefined, { urn })
            case "netbird:index/dnsSettings:DnsSettings":
                return new DnsSettings(name, <any>undefined, { urn })
            case "netbird:index/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "netbird:index/nameserverGroup:NameserverGroup":
                return new NameserverGroup(name, <any>undefined, { urn })
            case "netbird:index/network:Network":
                return new Network(name, <any>undefined, { urn })
            case "netbird:index/networkResource:NetworkResource":
                return new NetworkResource(name, <any>undefined, { urn })
            case "netbird:index/networkRouter:NetworkRouter":
                return new NetworkRouter(name, <any>undefined, { urn })
            case "netbird:index/peer:Peer":
                return new Peer(name, <any>undefined, { urn })
            case "netbird:index/personalAccessToken:PersonalAccessToken":
                return new PersonalAccessToken(name, <any>undefined, { urn })
            case "netbird:index/policy:Policy":
                return new Policy(name, <any>undefined, { urn })
            case "netbird:index/postureCheck:PostureCheck":
                return new PostureCheck(name, <any>undefined, { urn })
            case "netbird:index/route:Route":
                return new Route(name, <any>undefined, { urn })
            case "netbird:index/setupKey:SetupKey":
                return new SetupKey(name, <any>undefined, { urn })
            case "netbird:index/user:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("netbird", "index/accountSettings", _module)
pulumi.runtime.registerResourceModule("netbird", "index/dnsSettings", _module)
pulumi.runtime.registerResourceModule("netbird", "index/group", _module)
pulumi.runtime.registerResourceModule("netbird", "index/nameserverGroup", _module)
pulumi.runtime.registerResourceModule("netbird", "index/network", _module)
pulumi.runtime.registerResourceModule("netbird", "index/networkResource", _module)
pulumi.runtime.registerResourceModule("netbird", "index/networkRouter", _module)
pulumi.runtime.registerResourceModule("netbird", "index/peer", _module)
pulumi.runtime.registerResourceModule("netbird", "index/personalAccessToken", _module)
pulumi.runtime.registerResourceModule("netbird", "index/policy", _module)
pulumi.runtime.registerResourceModule("netbird", "index/postureCheck", _module)
pulumi.runtime.registerResourceModule("netbird", "index/route", _module)
pulumi.runtime.registerResourceModule("netbird", "index/setupKey", _module)
pulumi.runtime.registerResourceModule("netbird", "index/user", _module)
pulumi.runtime.registerResourcePackage("netbird", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:netbird") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
